philanthropy-u/edx-platform

common/djangoapps/student/migrations/0009_auto_20170830_1048.py, common/djangoapps/student/migrations/0009_userprofile_is_poc.py, common/djangoapps/student/models.py, common/djangoapps/student/views.py, lms/static/sass/_build-lms-v1.scss, lms/static/sass/_learner-dashboard.scss, lms/static/sass/_poc-dashboard.scss, lms/templates/dashboard.html, lms/templates/registration/activate_account_notice.html
Signed-off-by: Shahbaz Nazir <shahbaz.nazir@arbisoft.com>
=> Add different dashboards for learner and POC

common/djangoapps/student/middleware.py
Shared token should automatically be deleted on each logout hence nodebb will not have persistent log in.
=> Session sharing bug fix

common/djangoapps/student/middleware.py
=> Added domain to session sharing middleware

requirements/edx/github.txt
Audio xblock with transcript view
=> Audio xblock with transcript view

common/lib/nodebb_client/client.py, common/lib/nodebb_client/users.py
=> Logging added for testing purpose 

common/djangoapps/student/views.py, lms/djangoapps/courseware/views/views.py
- Dashboard reverted to old version
- Tag on the enrolled courses
=> Dashboard reverted to old version

cms/envs/common.py, common/djangoapps/student/middleware.py, lms/envs/common.py
Updated root domain for session sharing
=> Zee pk/global config

common/djangoapps/nodebb/signals/handlers.py, common/lib/nodebb_client/users.py
=> Modified signal to activate deactivate a user on nodebb  [#371]

lms/djangoapps/third_party_surveys/migrations/0001_initial.py
=> Review added migration [#LP-427]

openedx/core/djangoapps/timed_notification/tasks.py
=> Review changed scheduling time for a task [For testing purposes] 

openedx/core/djangoapps/timed_notification/tasks.py
* reverted time for celery task
=> Review reverted time for celery task 

common/djangoapps/nodebb/helpers.py, common/djangoapps/nodebb/migrations/0002_teamgroupchat.py, common/djangoapps/nodebb/models.py, common/djangoapps/nodebb/signals/handlers.py, common/lib/nodebb_client/client.py, common/lib/nodebb_client/groups.py, lms/djangoapps/teams/static/teams/js/views/team_card.js, lms/djangoapps/teams/static/teams/js/views/team_profile.js, lms/djangoapps/teams/static/teams/js/views/teams.js, lms/djangoapps/teams/static/teams/templates/group.underscore
* Added **TeamGroupChat** Model to store **room_id** of NodeBB
* Migration files added
* NodeBB client updated [**Group** Class overrided]
* API's added in **ForumGroup**
* Signals added to addd, update, remove group on **NodeBB** whenever **team** info changes
* Signals added to update **group_info** on NodeBB whenever a new member added or deleted in a **team**
connects #LP-97
=> Review added signals [#LP-97]

cms/envs/common.py
* Added teamsapp in cms because nodebb app has dependency on this app
connects #LP-97
=> Review added teams app in cms [#LP-97]

cms/envs/common.py, common/djangoapps/nodebb/helpers.py
=> Review added check [#LP-97]

lms/djangoapps/teams/static/teams/templates/group.underscore
=> Review edited url for nodebb chat [#LP-97]

lms/djangoapps/teams/static/teams/templates/group.underscore
=> Review added fix for NodeBB chat [#LP-97]

lms/djangoapps/student_dashboard/views.py
@omairshamshir Please review the code I have changed to solve this bug: "When someone enrolled in any recommended course. Then it should not appear in recommended courses tab."
=> exclude enrolled course from recommended courses

lms/djangoapps/oef/views.py, lms/djangoapps/onboarding/decorators.py, lms/djangoapps/onboarding/forms.py, lms/djangoapps/onboarding/helpers.py, lms/djangoapps/onboarding/models.py, lms/djangoapps/onboarding/urls.py, lms/djangoapps/onboarding/views.py, lms/urls.py
* Updates for LP-584
* Add myaccount pages
* Fix my account page bugs
* Updates for LP-584
* Add myaccount pages
* Fix my account page bugs
* Add my organizations pages
* LP-584 update my organization pages backend logic
* LP-584 update account setting form
* LP-584 update get_user_organizations
* LP-584 Update logic to edit organization admin
* LP-584 Update logic to edit organization admin
* LP-584 Update onboarding step-4 tooltips
* LP-584 Push changes requested in review
=> Mnadeem/lp 584 (#209)

lms/djangoapps/onboarding/forms.py, requirements/edx/github.txt
* Update ora installation url
* Add tooltips at update org details page
=> Update ora link (#217)

openedx/core/djangoapps/timed_notification/tasks.py
* Fix: named argument fix
* Improve: import fix
=> Fix: named argument fix (#221)

lms/djangoapps/philu_api/views.py
Please review and merge my changes to develop.
=> profile form update changes from nodebb

lms/djangoapps/onboarding/admin.py, lms/djangoapps/onboarding/constants.py, lms/djangoapps/onboarding/forms.py, lms/djangoapps/onboarding/models.py, lms/djangoapps/onboarding/views.py, lms/djangoapps/philu_api/urls.py, lms/djangoapps/philu_api/views.py, lms/djangoapps/teams/static/teams/js/views/team_card.js, lms/djangoapps/teams/static/teams/js/views/team_profile.js
- Fix Organization partners missing history bug
- Fix Organization Metrics missing history bug
- Show users avatar at teams page for chat
=> Onboarding history fix

lms/djangoapps/onboarding/forms.py, lms/djangoapps/philu_overrides/views.py
- Disable is_currently_employed checkbox at registration page if user is landing here for admin registration
=> Disable is_currently_employed checkbox

common/djangoapps/nodebb/admin.py, common/djangoapps/nodebb/migrations/0003_auto_20180312_1021.py, common/djangoapps/nodebb/models.py, lms/djangoapps/oef/migrations/0011_auto_20180312_1021.py, lms/djangoapps/onboarding/migrations/0013_auto_20180312_1021.py
- Add missing migrations for old fields label changes
=> Increase community_url max_length and add model at admin

common/lib/xmodule/xmodule/js/src/video/01_initialize.js, common/lib/xmodule/xmodule/js/src/video/03_video_player.js, lms/djangoapps/onboarding/forms.py, openedx/core/djangoapps/user_api/views.py
=> Video Transcript

lms/djangoapps/onboarding/forms.py
=> Block duplicate call to community API in case of userextendedprofile

lms/djangoapps/instructor/enrollment.py
Course url should be the actuall (does not matter whether it is rerun or not) but course about url should be the parent link (if it is a rerun).
=> make course about url to the main course and course url to re-run url

lms/djangoapps/onboarding/decorators.py, lms/djangoapps/onboarding/email_utils.py, lms/djangoapps/onboarding/forms.py, lms/djangoapps/onboarding/helpers.py, lms/djangoapps/onboarding/middleware.py, lms/djangoapps/onboarding/migrations/0002_populate_initial_data.py, lms/djangoapps/onboarding/models.py, lms/djangoapps/onboarding/tests/test_views.py, lms/djangoapps/onboarding/views.py
fix PEP8 issues in onbarding module
=> fix PEP8 issues in onbarding module

requirements/edx/github.txt
Removed caution text from peer assessment download attachment.
=> LP-992 Remove caution text

requirements/edx/github.txt
Updated ora repository hash to commit "Removed caution text from peer assessment download attachment"
=> Updated Ora Repo hash

requirements/edx/github.txt
Reverts philanthropy-u/edx-platform#721
=> Revert "faraz/LP-1089_ora-reskin"

lms/djangoapps/philu_overrides/courseware/views/views.py, lms/static/js/courseware/certificates_api.js
added case in generate_user_cert where staff generates user's certificate through progress page
=> LP-1189 - Instructor Student Certificate

requirements/edx/github.txt
updated commit version for edx-ora2
=> LP-1196 - Peer Assessment Followup Email Bug

common/djangoapps/custom_settings/models.py, lms/djangoapps/philu_api/helpers.py, lms/djangoapps/philu_overrides/views.py
Added social sharing for facebook and linkedin
=> Saad LP-1237 LP-1240

lms/djangoapps/philu_api/helpers.py
Added sharing for twitter: 1239
=> Added sharing for twitter: 1239

lms/djangoapps/philu_api/helpers.py, lms/djangoapps/philu_overrides/views.py, lms/envs/common.py
Fixed a bug where course title wasnt being picked up
Moved default image name to lms/common (doesnt exist in settings)
rewritten helper code to improve readiblity and reduce lines
=> Saadp LP 1237, 1239, 1240

lms/djangoapps/philu_api/helpers.py, lms/envs/common.py
=> Saad/LP-1259 Added sharing via email

common/djangoapps/nodebb/signals/handlers.py
I dedicate this PR to @RanaWaqar7550
=> avoided extra unenrollment sync with nodebb

common/djangoapps/nodebb/signals/handlers.py, lms/djangoapps/philu_overrides/helpers.py, lms/djangoapps/philu_overrides/philu_third_party_auth/custom_backends.py, lms/djangoapps/philu_overrides/user_api/views.py, lms/envs/aws.py, lms/static/js/student_account/views/LoginView.js, lms/static/js/student_account/views/RegisterView.js, lms/templates/student_account/form_status.underscore, openedx/core/djangoapps/user_api/views.py
Added SSO with facebook functionality and design
=> Lp 1272, LP 1270 Saad/Hassan

lms/djangoapps/philu_overrides/helpers.py, lms/djangoapps/philu_overrides/philu_third_party_auth/custom_backends.py, lms/djangoapps/philu_overrides/user_api/views.py, lms/envs/aws.py, lms/static/js/student_account/views/LoginView.js, lms/static/js/student_account/views/RegisterView.js, lms/templates/student_account/form_status.underscore, openedx/core/djangoapps/user_api/views.py
Reverts philanthropy-u/edx-platform#884
=> Revert "Lp 1272 design merge"

lms/djangoapps/philu_overrides/helpers.py, lms/djangoapps/philu_overrides/philu_third_party_auth/custom_backends.py, lms/djangoapps/philu_overrides/user_api/views.py, lms/envs/aws.py, lms/static/js/student_account/views/FormView.js, lms/static/js/student_account/views/LoginView.js, lms/static/js/student_account/views/RegisterView.js, lms/templates/student_account/form_status.underscore, openedx/core/djangoapps/user_api/views.py
=> Saad LP1270/1272/1292/1271

lms/djangoapps/philu_overrides/philu_third_party_auth/custom_backends.py, lms/envs/aws.py
Customized GoogleOAuth Provider to work without google plus api using the followng resources:
https://github.com/python-social-auth/social-core/issues/300
https://github.com/python-social-auth/social-core/pull/301
=> Saad LP-1271

common/djangoapps/third_party_auth/settings.py, lms/djangoapps/philu_overrides/user_api/views.py
Fixed name changing on login with new provider
=> Fixed name changing on login with new provider

openedx/features/student_certificates/views.py
Integrated LinkedIn sharing for Course cerificate
=> Integrated LinkedIn sharing for course certificate

common/djangoapps/third_party_auth/settings.py, lms/djangoapps/philu_overrides/helpers.py, lms/djangoapps/philu_overrides/philu_third_party_auth/custom_backends.py, lms/djangoapps/philu_overrides/user_api/views.py, lms/envs/aws.py, lms/static/js/student_account/views/FormView.js, lms/static/js/student_account/views/LoginView.js, lms/static/js/student_account/views/RegisterView.js, lms/templates/student_account/form_status.underscore, openedx/core/djangoapps/user_api/views.py
Integrated Single Sign on for google, facebook, linkedin
=> Saad LP-1272 LP-1270 LP-1271 LP-1292

lms/envs/common.py
updated notification from email address
=> LP-1315 updated notification from email address

openedx/features/split_registration/forms.py, openedx/features/split_registration/views.py
removed is_emp_location_different from backend
=> removed city from "you" tab in split registration

lms/djangoapps/philu_api/helpers.py, lms/djangoapps/philu_overrides/constants.py, lms/djangoapps/philu_overrides/views.py, openedx/features/split_registration/helpers.py
sharing popup after enrollment added: facebook, email
pre-req is branch imran/LP-1306
=> added sharing popup

lms/djangoapps/onboarding/middleware.py
fixed user redirection to correct flow when coming from nodebb
=> fixed user redirection to correct flow when coming from nodebb

lms/djangoapps/philu_api/helpers.py, lms/djangoapps/philu_overrides/constants.py, lms/djangoapps/philu_overrides/views.py, openedx/features/split_registration/helpers.py
Added social sharing after enroll
=> Added social sharing after enroll

lms/djangoapps/philu_overrides/teams/serializers.py, lms/djangoapps/teams/static/teams/js/views/edit_team.js, lms/djangoapps/teams/static/teams/templates/edit-team.underscore, lms/djangoapps/teams/views.py
Add our own serializer for teams creation and updated validation on serializers.
=> appied front-end and back-end validation on teams creation

openedx/features/split_registration/forms.py
=> LP-1381 LP-1297

lms/djangoapps/teams/static/teams/templates/team-member.underscore
=> added target _blank into team profile view

lms/djangoapps/onboarding/views.py, openedx/features/split_registration/views.py
- fixed bugs where user grantee opt in consents were not being saved during account update
=> LP-1415 LP-1414

common/djangoapps/util/philu_utils.py, lms/djangoapps/philu_overrides/user_api/views.py, lms/djangoapps/philu_overrides/views.py, openedx/features/student_account/views.py
added utm param saving using session
=> Saad LP-1426 using Session Approach

common/djangoapps/util/philu_utils.py, lms/djangoapps/philu_overrides/user_api/views.py, lms/djangoapps/philu_overrides/views.py, openedx/features/student_account/views.py
=> Saad LP-1426 using session

common/djangoapps/nodebb/migrations/0004_auto_20190524_0700.py, common/djangoapps/nodebb/models.py, common/djangoapps/nodebb/signals/handlers.py, openedx/features/teams/helpers.py, openedx/features/teams/views.py
=> added join community

lms/static/js/student_account/views/FormView.js
[LP-1431](https://philanthropyu.atlassian.net/browse/LP-1431)
[LP-1432](https://philanthropyu.atlassian.net/browse/LP-1432)
[LP-1433](https://philanthropyu.atlassian.net/browse/LP-1433)
[LP-1434](https://philanthropyu.atlassian.net/browse/LP-1434)
[LP-1436](https://philanthropyu.atlassian.net/browse/LP-1436)
[LP-1446](https://philanthropyu.atlassian.net/browse/LP-1446)
=> Registration event tracking in old and new flow

common/djangoapps/nodebb/signals/handlers.py, common/lib/nodebb_client/categories.py, openedx/features/teams/helpers.py, openedx/features/teams/views.py
Removed join and leave from nodebb_client/categories and used join and un_join from nodebb/users
Removed unused redundant method _get_group_data and description in nodebb handlers
Moved get_user_recommended_teams to teams/helpers
Made a method get_user_course_with_access in helpers
use get_alphabetical_topics from lms.djangoapps.teams.views instead of duplicating code
=> Implemented review for faraz/LP-1341 branch

openedx/features/teams/helpers.py
=> fix for chat embed view

common/djangoapps/nodebb/signals/handlers.py, common/lib/nodebb_client/categories.py, openedx/features/teams/helpers.py, openedx/features/teams/views.py
1341 Review + Hotfix for chat 404 issue
=> 1341 Review + Hotfix for chat 404 issue

common/djangoapps/nodebb/signals/handlers.py, common/lib/nodebb_client/categories.py, lms/static/js/student_account/views/FormView.js, openedx/features/teams/helpers.py, openedx/features/teams/views.py
=> Release v 1.29

lms/static/js/student_account/views/FormView.js
Updating GTM event and adding event label for Registration page 0 event
**Note:** This PR has a dependency on[ PR-860](https://github.com/philanthropy-u/philu-edx-theme/pull/860) of Philu-edx-theme repo
=> Tracking registration and measurement events on GTM

common/djangoapps/nodebb/helpers.py, common/djangoapps/nodebb/tasks.py, common/djangoapps/philu_commands/management/commands/archive_past_courses_communities.py, common/djangoapps/philu_commands/management/commands/archive_past_courses_teams.py, common/lib/nodebb_client/categories.py
Added new command to archive course communities including mini-communities on course end
=> LP-1410 Archive Communities on Course End

common/lib/xmodule/xmodule/js/src/video/04_video_control.js
Adding GTM event for video. This PR resolves following ticket:
**[LP-1444](https://philanthropyu.atlassian.net/browse/LP-1444)** Events Tracking: Media Engagement - Video
**Note**: This PR has a corresponding [PR-866](https://github.com/philanthropy-u/philu-edx-theme/pull/866) in theme
=> LP-1444 GTM event tracking for video

requirements/edx/github.txt
Adding reference of audio xblock latest commit
=> Adding reference of audio xblock latest commit

common/lib/xmodule/xmodule/js/src/video/04_video_control.js, requirements/edx/github.txt
Updating GTM event for video to cater all scenarios. This PR resolves following ticket:
**[LP-1444](https://philanthropyu.atlassian.net/browse/LP-1444)** Events Tracking: Media Engagement - Video
=> LP-1444 Updating GTM event for video

common/lib/xmodule/xmodule/js/src/video/04_video_control.js, requirements/edx/github.txt
Adding GTM event for video and updating AudioXBlock reference
=> LP-1444 Adding GTM event for video

.coveragerc, cms/djangoapps/contentstore/tasks.py, cms/djangoapps/contentstore/views/course.py, cms/envs/aws.py
Please go through core changes 1-5 in **edX Ironwood Upgrade - Spike story document** before review.
=> Moved core change 1 to 5 in Ironwood

common/djangoapps/student/migrations/0016_historicaluserprofile.py, common/djangoapps/student/migrations/0017_auto_20171219_0925.py, common/djangoapps/student/models.py
Please go through core changes 14-23 especially comments in edX Ironwood Upgrade - Spike story document before review.
=> LP-1475 - Move core change 14 to 23 in Ironwood

common/djangoapps/course_modes/views.py, common/djangoapps/student/models.py, lms/djangoapps/courseware/views/views.py, lms/djangoapps/philu_overrides/courseware/tasks.py, lms/djangoapps/philu_overrides/helpers.py, lms/djangoapps/philu_overrides/tasks.py, lms/djangoapps/philu_overrides/user_api/views.py, lms/djangoapps/philu_overrides/views.py, openedx/core/djangoapps/timed_notification/core.py, openedx/core/djangoapps/user_authn/views/register.py, openedx/features/student_account/views.py, openedx/features/student_certificates/views.py
[LP-1514](https://philanthropyu.atlassian.net/browse/LP-1514)
=> Change imports of student app views according to structure change

lms/djangoapps/philu_overrides/user_api/views.py, lms/envs/common.py, lms/envs/devstack.py, lms/envs/test.py, openedx/features/student_account/views.py
[LP-1520](https://philanthropyu.atlassian.net/browse/LP-1520)
=> Password policy updated for philu according to new password policy in ironwood

lms/djangoapps/philu_overrides/user_api/views.py, lms/djangoapps/philu_overrides/views.py, openedx/features/student_account/views.py
[LP-1533](https://philanthropyu.atlassian.net/browse/LP-1533)
=> Removed PasswordHistory usage

cms/djangoapps/contentstore/tasks.py, cms/envs/common.py, openedx/features/cms/helpers.py
Added new app openedx/features/cms 
changed re_run creation task. Added method that performs operations post-creation 
set module release and due dates
=> Backend Implementation of setting course module dates on basis of course start date/open-date

openedx/features/cms/helpers.py
=> LP-1491 Hotfix

common/djangoapps/philu_commands/management/commands/notify_non_active_users.py, common/lib/mandrill_client/client.py, openedx/core/djangoapps/timed_notification/notifications.py, openedx/features/ondemand_email_preferences/helpers.py, openedx/features/ondemand_email_preferences/utils.py
Schedule notification for on demand course
=> sent schedule notification for on demand course

openedx/features/cms/helpers.py
This PR automate ORA dates
**[LP-1498](https://philanthropyu.atlassian.net/browse/LP-1498)** Backend Implementation of setting course ORA assessments/assignments dates on basis of course start/end date
=> LP-1498 Backend implementation of setting course ORA dates during re-run

openedx/features/cms/helpers.py
This PR fixes issue with changed date flags, in backend implementation of ORA automation
**[LP-1498](https://philanthropyu.atlassian.net/browse/LP-1498)** Backend Implementation of setting course ORA assessments/assignments dates on basis of course start/end date
=> LP-1498 Fixing issue in backend implementation of setting course ORA dates

common/static/common/templates/chats/chat_pane.underscore
Reverts philanthropy-u/edx-platform#1067
We are reverting this PR in context of [LP-1395](https://philanthropyu.atlassian.net/browse/LP-1395)
=> Revert "Removed `common/static/common/templates/chats/chat_pane.underscore`"

lms/static/js/student_account/views/FormView.js, lms/static/js/student_account/views/RegisterView.js
This PR fixes bug related to GTM registration page 0 event
**[LP-1549](https://philanthropyu.atlassian.net/browse/LP-1549)** Registration Page 0 Event Triggering on Login page
=> LP-1549 Fixing GTM registration page 0 bug

openedx/features/cms/helpers.py, openedx/features/cms/views.py
Fix: Bug regarding enrollment start/end date
=> [LP-1506] Fix: Bug regarding enrollment start/end date

requirements/philu/base.txt
- In ficus this dependency was being installed by some other package
which Ironwood might has removed so we need to add it
=> Add w3lib in philu requirements

common/djangoapps/mailchimp_pipeline/signals/handlers.py, common/lib/mandrill_client/client.py, lms/djangoapps/onboarding/handlers.py, lms/djangoapps/onboarding/helpers.py
- Allow registered learners to change their email address - Part 1: Backend implementation
- This PR allow admin to change email in NodeBB, Mailchimp and sends email to old and new emails
=> LP-1099 Change email in NodeBB, Mailchimp when admin updates it

cms/djangoapps/contentstore/tasks.py, cms/envs/common.py, cms/urls.py, openedx/features/cms/helpers.py, openedx/features/cms/urls.py, openedx/features/cms/views.py
- Integrate changes related to custom_settings
- Integrate features/cms app
please update the status of each file [in this document](https://docs.google.com/spreadsheets/d/1dRL0yMDstsc8P7_01gPkEWsPvMfA9hceFlgjjwe9J08/edit?usp=sharing), while reviewing
And here is the [reference PR](https://github.com/philanthropy-u/edx-platform/pull/1151/files)
=> Integrate_changes_04/04_in_ironwood_file_1_to_8_and_61_65

common/djangoapps/nodebb/helpers.py, common/djangoapps/nodebb/signals/handlers.py, common/djangoapps/nodebb/tasks.py, common/djangoapps/nodebb/views.py, common/djangoapps/philu_commands/management/commands/archive_past_courses_communities.py, common/djangoapps/philu_commands/management/commands/autoscore_ondemand_course_ora.py, common/djangoapps/philu_commands/management/commands/notify_non_active_users.py, common/djangoapps/philu_commands/management/commands/send_ondemand_weekly_emails.py
please update the status of each file [in this document](https://docs.google.com/spreadsheets/d/1dRL0yMDstsc8P7_01gPkEWsPvMfA9hceFlgjjwe9J08/edit?usp=sharing), while reviewing
And here is the [reference PR](https://github.com/philanthropy-u/edx-platform/pull/1151/files)
=> Integrate_changes_04/04_in_ironwood_file_9_to_20

common/djangoapps/philu_commands/management/commands/sync_users_with_mailchimp.py
Pass update_existing: True for mailchimp request body.
=> Handle RelatedObjectDoesNotExist exception

common/djangoapps/mailchimp_pipeline/signals/handlers.py, common/lib/mandrill_client/client.py, lms/djangoapps/onboarding/handlers.py, lms/djangoapps/onboarding/helpers.py
Update email in NodeBB and MailChimp when admin updates it
=> Integrate ficus changes release-v-1.37 LP-1099

common/djangoapps/philu_commands/management/commands/send_ondemand_reminder_emails.py, common/lib/mandrill_client/client.py
Implement send reminder emails
=> Integrate ficus changes release 1.37 LP-1510

lms/djangoapps/homepage/views.py
**Context:**
Featured courses on dashboard are not showing, when `is_featured` flag on CMS is set to true
**Fix:**
Minor fix in code; Conditional statement updated
=> Fixing featured courses on dashboard

lms/djangoapps/philu_api/views.py
**Fix**: Set `Access-Control-Allow-Origin` header before sending response
=> mabdullahz/LP-1619: [FIX]  Fix NodeBB CORS error on AJAX call

openedx/features/partners/g2a/views.py, openedx/features/partners/helpers.py
https://philanthropyu.atlassian.net/browse/LP-1633
- Implmenet recommendation logic
=> LP-1633_implement_g2a_recommnedations_page

lms/djangoapps/onboarding/forms.py, lms/djangoapps/onboarding/models.py, lms/djangoapps/onboarding/views.py
=> Registration flow changed

openedx/features/partners/g2a/constants.py, openedx/features/partners/g2a/views.py
Creating bridge table between user and partner table
=> LP-1637 Creating bridge table between user and partner table

openedx/features/partners/give2asia/views.py
fixed syncing of Userprofile on nodebb
=> fixed syncing of Userprofile on nodebb

openedx/features/partners/give2asia/constants.py
LP-1637 Adding comments for default data
=> LP-1637 Adding comments for default data

lms/djangoapps/grades/models.py
Fixed case of circular dependency between VisibleBlocks and PersistentSubsectionGrade
=> [Already reviewed refreshing dev]Fixed case of circular dependency

common/djangoapps/nodebb/helpers.py, common/djangoapps/nodebb/signals/handlers.py, common/djangoapps/nodebb/tasks.py, common/djangoapps/philu_commands/management/commands/sync_users_with_nodebb.py, openedx/features/partners/give2asia/views.py
reverted previous code for the task: task_create_user_on_nodebb since a problem arose regarding passing object to the task
manually called nodebb task to activate user
=> Updated task for activation

common/djangoapps/philu_commands/management/commands/fetch_course_structures.py
Added new command to fetch course structures. it takes course ids as input and returns course_structures for only those ids which are valid
=> [LP-1667] Added new command to fetch course structures

lms/urls.py, openedx/features/badging/helpers.py, openedx/features/badging/urls.py, openedx/features/badging/views.py
- Backend implementation for showing badges on trophy case
=> LP-1592 Backend implementation for showing badges on Trophycase

openedx/features/partners/give2asia/forms.py, openedx/features/partners/views.py
Updating backend messages for email and moving CSRF exemption from partners (Give2Asia) registration view API
=> LP1646 Updating backend messages for email

lms/urls.py, openedx/features/courseware/constants.py, openedx/features/courseware/helpers.py, openedx/features/courseware/urls.py, openedx/features/courseware/views.py
[LP-1612](https://philanthropyu.atlassian.net/browse/LP-1612)
=> LP-1612: Add an api to fetch pre and post assessment score

openedx/features/partners/forms.py, openedx/features/partners/urls.py, openedx/features/partners/views.py
Following changes were made:
**`forms.py`** [New File]: Form validation method `validate_user_using_email` was added to check if the user against the reset password request is a registered user or not.
**`urls.py`**: A new url was added to call the reset password view.
**`views.py`**: A new view was added named `password_reset_request` which uses the previously mentioned form validator to check if the user exists, and if it does, sends a reset password email to the user using the already implemented `password_change_request_handler`.
=> mabdullahz/LP-1639: G2A RegFlow: Reset Password

lms/urls.py, openedx/features/courseware/constants.py, openedx/features/courseware/helpers.py, openedx/features/courseware/urls.py, openedx/features/courseware/views.py
[LP-1612](https://philanthropyu.atlassian.net/browse/LP-1612)
=> Add an api to fetch pre and post assessment score

openedx/features/badging/admin.py, openedx/features/badging/constants.py, openedx/features/badging/helpers.py, openedx/features/badging/models.py, openedx/features/badging/urls.py, openedx/features/badging/views.py
This PR has following features:
1. Show team badges for only joined teams in a course
2. Do not show team badges if team feature is disabled
3. Do not show team badges if team is not configured for a course
4. Added a flag, if user has not joined any team in course
5. Optimizing assign badge code
=> LP-1593 Backend implementation for showing My badges in course

common/djangoapps/philu_commands/management/commands/auto_generate_certificates_for_open_courses.py, common/djangoapps/philu_commands/management/commands/generate_certificates_for_early_no_info.py
Added management command to auto-generate certificates for courses currently running
=> [LP-1621]Added management command to auto-generate certificates for courses currently running

openedx/features/badging/helpers.py, openedx/features/badging/views.py
LP-1594 Showing trophy case page
=> LP-1594 Showing trophy case page

common/djangoapps/nodebb/helpers.py, openedx/features/partners/give2asia/constants.py, openedx/features/partners/give2asia/forms.py, openedx/features/partners/give2asia/views.py
Backend implementation of adding organization to G2A reg flow
=> LP-1685 Backend - Add organization to G2A reg flow

common/djangoapps/nodebb/helpers.py, openedx/features/partners/give2asia/views.py
LP-1685:
Reverting excluded signal for G2A activation
Changed order of activation and registration signal
=> LP-1685 Reverting excluded signal for G2A activation

openedx/features/partners/give2asia/forms.py, openedx/features/partners/give2asia/views.py
**Acceptance Criteria:**
1. The country should be start recoding in `UserProfile` model.
=> [CHNAGE][LP-1686] record country to `UserProfile` model.

openedx/features/partners/give2asia/constants.py
Updating total employees value from **NA** to **NOTAPP**
=> LP-1685 Making total employees value consistent to staging and prod

openedx/features/partners/give2asia/constants.py, openedx/features/partners/give2asia/views.py
Allow G2A-tagged learners to skip "Org Details" step
=> Zahid/lp 1756 Hot fix: Allow G2A-tagged learners to skip "Org Details" step

lms/djangoapps/philu_api/helpers.py
Import removed and another PR created to make it simpler for @saad-waqar to handle changes.
=> Remove unused import

.coveragerc, openedx/features/badging/tests/factories.py, openedx/features/badging/tests/test_helpers.py, openedx/features/badging/tests/test_model_userbadge.py, openedx/features/badging/tests/test_views.py
Unit test for badge assignment, my badges and trophy case
=> LP-1592 LP-1593 Unit test for badge assignment, my badges and trophy case

common/djangoapps/third_party_auth/pipeline.py
LP-1720: Added support of SSO to cater popup redirection
=> LP-1720: Added support of SSO to cater popup redirection

common/lib/mandrill_client/client.py, openedx/features/badging/constants.py, openedx/features/badging/handlers.py, openedx/features/badging/helpers.py, openedx/features/badging/models.py, openedx/features/badging/tasks.py
[LP-1602](https://philanthropyu.atlassian.net/browse/LP-1602)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1077)
This is partial PR but can be merged
=> LP-1602 Sending email when user earn badge

openedx/features/badging/constants.py, openedx/features/badging/handlers.py, openedx/features/badging/helpers.py
[LP-1596](https://philanthropyu.atlassian.net/browse/LP-1596)
=> LP-1596 Integrate backend implementation with html for My badges

openedx/features/badging/constants.py, openedx/features/badging/handlers.py, openedx/features/badging/helpers.py, openedx/features/badging/models.py, openedx/features/badging/tasks.py
[LP-1602](https://philanthropyu.atlassian.net/browse/LP-1602)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1086)
Send user notification which will appear in top right navigation bar for earning team's badge.
=> LP-1602 Send notification on earning new badge

openedx/features/badging/constants.py, openedx/features/badging/handlers.py, openedx/features/badging/helpers.py
[LP-1596](https://philanthropyu.atlassian.net/browse/LP-1596)
=> Usman/lp 1596 Integrate backend implementation with html for My badges

openedx/features/specializations/urls.py, openedx/features/specializations/views.py
Add specializations about page url.
=> Add specializations about page url

common/lib/mandrill_client/client.py, openedx/features/badging/constants.py, openedx/features/badging/handlers.py, openedx/features/badging/helpers.py, openedx/features/badging/models.py, openedx/features/badging/tasks.py
[LP-1602](https://philanthropyu.atlassian.net/browse/LP-1602) Implementation of Notification/email for earning badge
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1098)
=> LP-1602 Implementation of Notification/email for earning badge

common/djangoapps/mailchimp_pipeline/helpers.py, common/djangoapps/mailchimp_pipeline/tasks.py, common/djangoapps/mailchimp_pipeline/tests/test_tasks.py, common/djangoapps/philu_commands/management/commands/sync_users_with_mailchimp.py, lms/djangoapps/onboarding/models.py, openedx/core/djangoapps/user_api/views.py, openedx/features/student_account/forms.py, openedx/features/student_account/helpers.py, openedx/features/student_account/tests/test_helpers.py
[LP-1735](https://philanthropyu.atlassian.net/browse/LP-1735)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1095)
During the integration of reg-flow backend and front end, few changes were required from backend as well, those are implemented under this PR.
=> faraz/LP-1735: Integrate registration flow

openedx/features/student_account/forms.py
[LP-1735](https://philanthropyu.atlassian.net/browse/LP-1735)
Post fix
=> implement org name cleaner

openedx/features/badging/helpers.py
[LP-`596](https://philanthropyu.atlassian.net/browse/LP-1596)
=> LP-1596 Redirect user to team dashboard if user hasn't join any team

openedx/features/badging/tests/test_handlers.py, openedx/features/badging/tests/test_helpers.py
[LP-1602](https://philanthropyu.atlassian.net/browse/LP-1602)
Added unit tests for newly earned badge notification changes.
=> LP-1602 Implementation of Notification/email for earning badge Unit Tests

openedx/features/badging/tests/test_model_userbadge.py, openedx/features/badging/tests/test_tasks.py
[LP-1602](https://philanthropyu.atlassian.net/browse/LP-1602) Unit test for sending email when user earn badge
=> LP-1602 Unit test for sending email when user earn badge

common/lib/discovery_client/client.py, openedx/features/specializations/urls.py, openedx/features/specializations/views.py
- Add method to get active programs from discovery
[LP-1748](https://philanthropyu.atlassian.net/browse/LP-1748)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1113)
=> LP-1748 Add discovery_client to communicate with discovery service

lms/djangoapps/courseware/access.py, lms/djangoapps/philu_overrides/context_processor.py, lms/djangoapps/teams/views.py, openedx/core/lib/api/permissions.py, openedx/features/teams/mixins.py, openedx/features/teams/views.py
[LP-1804](https://philanthropyu.atlassian.net/browse/LP-1804)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1108)
Fix inconsistencies on LMS to enable a new reg-flow inactive user
=> LP-1804 Fix inconsistencies on LMS to enable a new reg-flow inactive user

common/djangoapps/mailchimp_pipeline/helpers.py, common/djangoapps/mailchimp_pipeline/signals/handlers.py, common/djangoapps/mailchimp_pipeline/tasks.py
[LP-1734](https://philanthropyu.atlassian.net/browse/LP-1734)
Looked through all the signals being called by the new registration flow, and made some minor changes as were thought required. Verified that all the data is being synced in MailChimp.
Refer to [this document](https://docs.google.com/document/d/1OjrsVBVH3zXLEjuu8xZUwCPi-UWNvCxaA9moX4IPZZo/edit#) for the process followed.
=> mabdullahz/LP-1734: Minor updates in MailChimp signals

common/djangoapps/third_party_auth/settings.py, lms/djangoapps/philu_overrides/philu_third_party_auth/context_processor.py, lms/djangoapps/philu_overrides/philu_third_party_auth/helpers.py, lms/envs/common.py, openedx/core/djangoapps/user_api/views.py, openedx/features/student_account/helpers.py
Changes added:
- utm params handled
- opt_in flag value is propagated with SSO
- handled automatic popup open
- handled second popup opening on register button
- handled fields being pre-filled
[LP-1784](https://philanthropyu.atlassian.net/browse/LP-1784)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1118)
=> LP-1784 Added changes to support SSO in new Regflow

openedx/features/partners/give2asia/views.py
[LP-1845](https://philanthropyu.atlassian.net/browse/LP-1845)
[philu-edx-theme PR ](https://github.com/philanthropy-u/philu-edx-theme/pull/###) @hassanarif426 is working on that.
=> Remove unused import which was breaking code

common/djangoapps/third_party_auth/middleware.py, common/djangoapps/third_party_auth/settings.py, lms/djangoapps/philu_overrides/philu_third_party_auth/context_processor.py
- Changed opt_in field location
- Changed opt_in checkbox design
- Added SSO confirmation message on second popup
- Added SSO Failure message on first popup
[LP-1835](https://philanthropyu.atlassian.net/browse/LP-1835)
[LP-1836](https://philanthropyu.atlassian.net/browse/LP-1836)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1127)
There are core changes in this PR
=> Changed OPT_IN field location and design | Added SSO messages

common/djangoapps/mailchimp_pipeline/signals/handlers.py, common/djangoapps/nodebb/signals/handlers.py, common/djangoapps/student/models.py, lms/djangoapps/onboarding/handlers.py, lms/djangoapps/onboarding/models.py
[LP-1728](https://philanthropyu.atlassian.net/browse/LP-1728)
Improve simple regflow signal flow and implementation
=> LP-1728 Improve simple regflow signal flow and implementation 

common/lib/discovery_client/client.py, lms/djangoapps/philu_overrides/views.py, openedx/features/specializations/helpers.py, openedx/features/specializations/views.py
[LP-1745](https://philanthropyu.atlassian.net/browse/LP-1745)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1125)
=> LP-1745 Implement specialization about view

openedx/features/specializations/views.py
[LP-1745](https://philanthropyu.atlassian.net/browse/LP-1745)
=> Fix TypeError

openedx/features/partners/views.py
1. `Line 23 + 32 + 110 + 137`: These optimizations were made under #1350, when we removed the philu_overrides regflow, and moved to actual edX one.
2. `Line 213 - 215`: This fix was made under @zahid-arbisoft 's #1425 PR.
=> mabdullahz/regflow-dev: Fix partner views moving g2a optimizations

common/lib/discovery_client/client.py, lms/djangoapps/philu_overrides/views.py, openedx/features/specializations/helpers.py, openedx/features/specializations/views.py
=> Zeshan/lp 1745 [Remerging after develop refresh]

lms/djangoapps/onboarding/migrations/0028_education_experience_skill.py, lms/djangoapps/onboarding/migrations/0029_auto_20200130_0957.py
=> Change dependencies to merge regflow

openedx/features/badging/helpers.py
[LP-1709](https://philanthropyu.atlassian.net/browse/LP-1709)
Team not enabled issue resolved
=> LP-1709 Team disabled issue resolved

openedx/features/job_board/apps.py, openedx/features/job_board/models.py, openedx/features/job_board/urls.py, openedx/features/job_board/views.py
[LP-1943](https://philanthropyu.atlassian.net/browse/LP-1943)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1153)
1. `urls.py`: Changed called view and modified the detail page regex to include more than one integer.
2. `views.py`: Use django generic ListView for the `JobsListView`. Override the `get_context_data` method to pass the `total_job_count` to template. Sort the objects by most recent first.
=> mabdullahz/LP-1943: Populate job listing page

common/lib/discovery_client/client.py, openedx/features/specializations/views.py
[LP-1747](https://philanthropyu.atlassian.net/browse/LP-1747)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1187)
Integrate course enrolment functionality on specialization about page
=> LP-1747 Integrate course enrolment functionality on specialization about page

openedx/features/partners/tests/factories.py, openedx/features/partners/tests/test_helpers.py, openedx/features/partners/tests/test_views.py
Fixed the broken test in Partners application also written the view related unit test and removed the unused commented code. 
[LP-1938](https://philanthropyu.atlassian.net/browse/LP-1938)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1481)
=> LP-1938 Update partners unit tests

openedx/features/partners/tests/factories.py, openedx/features/partners/tests/test_helpers.py, openedx/features/partners/tests/test_views.py
Fixed the broken test in Partners application also written the view related unit test and removed the unused commented code. 
[LP-1938](https://philanthropyu.atlassian.net/browse/LP-1938)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1486)
=> LP-1938 Update partners unit tests 

openedx/features/job_board/views.py
[LP-1945](https://philanthropyu.atlassian.net/browse/LP-1945)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1191)
Add search filter support Job Listing page and pass the relevant context to the template.
=> Job Board: Add search filter support Job Listing page

openedx/features/partners/tests/factories.py, openedx/features/partners/tests/test_helpers.py, openedx/features/partners/tests/test_views.py
=> Refreshed Develop PR 1938

common/lib/discovery_client/client.py, openedx/features/specializations/views.py
=> Refreshed Develop PR 1747

openedx/core/djangolib/testing/philu_utils.py, openedx/features/cms/tests/test_views.py, openedx/features/course_card/tests/test_course_date_views.py, openedx/features/course_card/tests/test_views.py, openedx/features/specializations/tests/mock_get_program_helpers.py, openedx/features/specializations/tests/test_views.py, openedx/features/student_certificates/tests/test_views.py, openedx/features/teams/tests/test_views.py
[LP-1745](https://philanthropyu.atlassian.net/browse/LP-1745)
=> LP-1745 Add unit tests for specialization about view

common/lib/discovery_client/client.py, openedx/features/specializations/views.py
=> Staging Refresh Merge 1747

openedx/features/partners/tests/factories.py, openedx/features/partners/tests/test_helpers.py, openedx/features/partners/tests/test_views.py
=> Staging Refresh Merge 1938

openedx/features/student_certificates/helpers.py
[LP-1937](https://philanthropyu.atlassian.net/browse/LP-1937)
Get program name from cache and display program certificate in My Certificates page.
=> Get program name from cache and display program certificate

openedx/features/student_certificates/constants.py, openedx/features/student_certificates/helpers.py, openedx/features/student_certificates/tests/test_helpers.py, openedx/features/student_certificates/tests/test_views.py, openedx/features/student_certificates/views.py
[LP-1642](https://philanthropyu.atlassian.net/browse/LP-1642)
=> LP-1642 Change default PDF download document name

openedx/features/idea/admin.py
[LP-2002](https://philanthropyu.atlassian.net/browse/LP-2002)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1231)
Added the 'favorites' attribute of idea model in raw_id_fields of the ModelAdmin
=> LP-2002 500 Error 'IDEAS' model on adding new idea

openedx/features/marketplace/decorators.py
redirect user to login if user is not authenticated, and to additional_information view if user is unaffiliated.
[LP-1970](https://philanthropyu.atlassian.net/browse/LP-1970)
=> LP-1970 OTHER Implement Marketplace Request Form

openedx/features/idea/api_views.py
[LP-1965](https://philanthropyu.atlassian.net/browse/LP-1965)
Integrate favoritre api
=> LP-1965 Integrate favoritre api

openedx/features/idea/api_views.py
[LP-1965](https://philanthropyu.atlassian.net/browse/LP-1965)
Change authentication classes to cater in active users
=> [LP-1965] Change authentication classes to cater inactive users

lms/urls.py
[LP-2067](https://philanthropyu.atlassian.net/browse/LP-2067)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1255)
=> LP-2067 Create 4 dummy pages on LP

openedx/features/marketplace/forms.py
[LP-2000](https://philanthropyu.atlassian.net/browse/LP-2000)
=> LP-2000 Create HTML for add marketplace request form

lms/urls.py
[LP-1870](https://philanthropyu.atlassian.net/browse/LP-1870)
Add urls to use waffle switches in JS
=> LP-1870 Hook smart referral dialog with reg-flow step 2

openedx/features/idea/forms.py
=> Change video_link label

lms/djangoapps/homepage/helpers.py, lms/djangoapps/homepage/urls.py
- Moved get_featured_courses function to helpers.py
[LP-2090](https://philanthropyu.atlassian.net/browse/LP-2090)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1283)
=> - Remove unused context from homepage view

common/djangoapps/philu_commands/helpers.py, common/djangoapps/philu_commands/management/commands/auto_generate_certificates_for_open_courses.py
[LP-2079](https://philanthropyu.atlassian.net/browse/LP-2079)
=> LP-2079 OTHER Do not send email that prompts learners to download.

openedx/features/course_card/tests/test_course_date_views.py, openedx/features/course_card/tests/test_views.py
PR was already[ reviewed and merged,](https://github.com/philanthropy-u/edx-platform/pull/1574) in develop have to recreate becuase I just refreshed the develop branch with master.
=> LP-2029 Fixed broken Unit tests.

openedx/features/course_card/tests/test_course_date_views.py, openedx/features/course_card/tests/test_views.py
[LP-2029](https://philanthropyu.atlassian.net/browse/LP-2029)
Fixed broken Unit test cases related to feature course card. test was mainly not working due to exception of course_overview object not found on create a course card a course_overview needed.
=> LP-2029 Fixed broken Unit test cases related to feature course card

common/djangoapps/philu_commands/management/commands/tests/test_mailchimp_commands.py, common/djangoapps/philu_commands/management/commands/tests/test_sync_users_with_nodebb_command.py
[LP-2037](https://philanthropyu.atlassian.net/browse/LP-2037)
=> LP-2037 Fix broken unit tests for philu_commands

openedx/features/philu_courseware/tests/test_competency_assessment_recording.py
[LP-2031](https://philanthropyu.atlassian.net/browse/LP-2031)
=> LP-2031: Fix reverse URL and add missing required entry in data

openedx/features/student_account/tests/test_display_notification.py
[LP-2032](https://philanthropyu.atlassian.net/browse/LP-2032)
=> LP-2032: Fix student_account breaking unit tests

common/djangoapps/nodebb/tests.py
[LP-2036](https://philanthropyu.atlassian.net/browse/LP-2036)
=> LP-2036: Fix nodebb app unit tests failing due to root imports

common/lib/mandrill_client/client.py, lms/urls.py, openedx/features/smart_referral/models.py, openedx/features/smart_referral/serializers.py, openedx/features/smart_referral/tasks.py, openedx/features/smart_referral/tests/factories.py, openedx/features/smart_referral/tests/test_tasks.py, openedx/features/smart_referral/tests/test_views.py, openedx/features/smart_referral/urls.py, openedx/features/smart_referral/views.py
[LP-1881](https://philanthropyu.atlassian.net/browse/LP-1881) Send initial referral invite and toolkit email
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1306)
Unit tests are included
=> LP-1881 Send initial referral invite and toolkit email

common/djangoapps/philu_commands/management/commands/auto_generate_certificates_for_open_courses.py
added logging because it is very difficult to debug on dev.
=> LP-2079 Do not send email that prompts learners to download certificate.

common/djangoapps/philu_commands/constants.py, common/djangoapps/philu_commands/management/commands/autoscore_ondemand_course_ora.py, openedx/features/assessment/constants.py, openedx/features/assessment/helpers.py, openedx/features/philu_utils/utils.py
[LP-2089](https://philanthropyu.atlassian.net/browse/LP-2089)
=> Autoscore first submission and ignore rest of the submissions

common/djangoapps/philu_commands/management/commands/auto_generate_certificates_for_open_courses.py
[LP-2079](https://philanthropyu.atlassian.net/browse/LP-2079)
=> [FIX] LP-2079 command getting broken, after adding logging.

lms/djangoapps/onboarding/choices.py, lms/djangoapps/onboarding/migrations/0030_add_new_fields_for_model_optimization.py
=> LP-2039 Postfix-correct choice label

common/djangoapps/philu_commands/management/commands/autoscore_ondemand_course_ora.py, openedx/features/assessment/helpers.py
[LP-2089](https://philanthropyu.atlassian.net/browse/LP-2089)
=> LP-2089 Order by submitted_at to get first submission instead of last submission

lms/djangoapps/onboarding/models.py, openedx/features/marketplace/helpers.py
[LP-1968](https://philanthropyu.atlassian.net/browse/LP-1968)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1314)
[NodeBB-Theme PR](https://github.com/philanthropy-u/nodebb-theme-philu-community/pull/585)
Added a new model method in organization model. (get_first_learner) As we need a first learner  user in marketplace template to create a Connect Chat URL.
=> LP-1968 Integrate Marketplace Request Connect functionality with Edx

common/djangoapps/philu_commands/constants.py, common/djangoapps/philu_commands/management/commands/autoscore_ondemand_course_ora.py, openedx/features/assessment/constants.py, openedx/features/assessment/helpers.py, openedx/features/philu_utils/utils.py
[LP-2089](https://philanthropyu.atlassian.net/browse/LP-2089)
=> LP-2089 Autoscore first submission and ignore rest of the submissions

openedx/features/smart_referral/api_views.py
Duplication contacts issue resolved
=> LP-1873-1878-1881 Dublication contacts issue resolved

openedx/features/assessment/helpers.py
[LP-2089](https://philanthropyu.atlassian.net/browse/LP-2089)
=> Add logs for multiple submission ids and pass submission uuid as str

lms/djangoapps/onboarding/choices.py, lms/djangoapps/onboarding/migrations/0030_add_new_fields_for_model_optimization.py
[LP-2039](https://philanthropyu.atlassian.net/browse/LP-2039)
Appended a missing ending bracket ')' in the value against the key 'hear_about_philanthropy_partner' in choices.HEAR_ABOUT_PHILANTHROPY
=> LP-2039 Postfix - correct HEAR_ABOUT value

lms/urls.py
Refreshed Develop: Remerging Already approved PR: https://github.com/philanthropy-u/edx-platform/pull/1631
=> Refreshed Develop: Remerging Already approved PR: #1631

openedx/features/marketplace/constants.py
[LP-2072](https://philanthropyu.atlassian.net/browse/LP-2072)
=> LP-2072 Backend Issues on Marketplace Request Form

openedx/features/teams/tests/test_serializers.py, openedx/features/teams/tests/test_views.py
[LP-2033](https://philanthropyu.atlassian.net/browse/LP-2033)
=> LP-2033 Fix broken unit tests of teams.

common/lib/nodebb_client/client.py, openedx/features/badging/tests/test_model_badge.py, openedx/features/badging/tests/test_views.py
[LP-2028](https://philanthropyu.atlassian.net/browse/LP-2028)
=> LP-2028 Fixing badging unittests

openedx/features/partners/views.py
[LP-2022](https://philanthropyu.atlassian.net/browse/LP-2022)
=> LP-2022 Fixing G2A registration and allow name with accented character

openedx/core/djangoapps/user_authn/views/register.py, openedx/features/partners/views.py
[LP-2022](https://philanthropyu.atlassian.net/browse/LP-2022) Fixing registration and allow name with accented character
=> LP-2022 Fixing registration and allow name with accented character

openedx/features/custom_fields/multiselect_with_other/db/fields.py, openedx/features/marketplace/views.py
[LP-2145](https://philanthropyu.atlassian.net/browse/LP-2145) 500 Error on Marketplace Landing Page on entering accented character in 'Other' fields
**Notes**
Some additional work done
- Using `DetailView` instead of `View`for marketplace request page view
=> LP-2145 Fixing accented character issue in Community Hub request form

common/djangoapps/philu_commands/management/commands/send_referral_follow_up_email.py, common/djangoapps/philu_commands/management/commands/tests/test_send_referral_follow_up_emails.py, openedx/features/smart_referral/tasks.py, openedx/features/smart_referral/tests/test_tasks.py
[LP-1877](https://philanthropyu.atlassian.net/browse/LP-1877)
- Filter query issue resolved for 3 days old referrals.
- Duplicate emails issue resolved.
=> LP-1877 Remove three days old referral issue resolved

openedx/features/course_card/helpers.py
[LP-2151](https://philanthropyu.atlassian.net/browse/LP-2151)
=> LP-2151 Specialization tag is not displaying on course catalog page.

lms/djangoapps/onboarding/choices.py, lms/djangoapps/onboarding/forms.py, lms/djangoapps/onboarding/migrations/0031_add_new_fields_for_model_optimization.py, lms/djangoapps/onboarding/migrations/0032_data_migration_model_optimization.py
Fixed is_interest_data_submitted flag and fixed typo in hear_about_philanthropyu keys
=> LP-2160: Fixed is_interest_data_submitted flag and fixed typo in hear_about_philanthropyu keys

common/djangoapps/philu_commands/management/commands/data_consistency_check_onboarding_optimization.py
[LP-2042](https://philanthropyu.atlassian.net/browse/LP-2042)
=> LP-2042 Update command for exception logging

openedx/features/job_board/forms.py
[LP-2146](https://philanthropyu.atlassian.net/browse/LP-2146)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1367)
No impact on unit test
=> LP-2146 Fixing issues on job board feature

openedx/features/custom_fields/multiselect_with_other/db/fields.py
[LP-2165](https://philanthropyu.atlassian.net/browse/LP-2165)
=> LP-2165 The other field in MultiSelectWithOther does not render comma(s)

openedx/features/custom_fields/multiselect_with_other/db/fields.py
[LP-2165](https://philanthropyu.atlassian.net/browse/LP-2165)
=> LP-2165 Empty tags issue resolved

openedx/features/student_certificates/constants.py, openedx/features/student_certificates/helpers.py
[LP-2167](https://philanthropyu.atlassian.net/browse/LP-2167) PDF certificate appearing in two pages
**Notes**
- No prior unit test written
- This is a potential fix, but it does not guarantee it will fix the issue on prod.
=> LP-2167 Fixing PDF certificate appearing in two pages

openedx/features/custom_fields/multiselect_with_other/db/fields.py
=> Rebase develop with master

lms/urls.py
[LP-2183](https://philanthropyu.atlassian.net/browse/LP-2183)
=> LP-2183 Remove faq url

openedx/features/philu_courseware/helpers.py, openedx/features/philu_courseware/models.py, openedx/features/philu_courseware/serializers.py, openedx/features/philu_courseware/tests/factories.py, openedx/features/philu_courseware/tests/test_competency_assessment_record_manager.py, openedx/features/philu_courseware/tests/test_helpers.py, openedx/features/philu_courseware/urls.py, openedx/features/philu_courseware/views.py
[LP-2161](https://philanthropyu.atlassian.net/browse/LP-2161)
=> LP-2161 Add api view to revert user post assessment attempts

openedx/features/xmodules/constants.py, openedx/features/xmodules/helpers.py, openedx/features/xmodules/tests/test_helpers.py
Add a new package 'tests'
Add a new file 'test_helpers.py'
[LP-2176](https://philanthropyu.atlassian.net/browse/LP-2176)
=> LP-2176 Write unit test(s) for xmodules

common/djangoapps/student/views/management.py, common/lib/mandrill_client/client.py, lms/djangoapps/onboarding/helpers.py, lms/djangoapps/onboarding/views.py
[LP-1544](https://philanthropyu.atlassian.net/browse/LP-1544)
Notifying the learner and implementing the update
=> LP-1544 Part-2 Allow registered learners to change their email address

openedx/features/specializations/templatetags/sso_meta_tag.py
[LP-1752](https://philanthropyu.atlassian.net/browse/LP-1752)
=> LP-1752 Django Custom SSO

common/djangoapps/custom_settings/tests/test_handlers.py
[LP-2180](https://philanthropyu.atlassian.net/browse/LP-2180) Fixing test method name in custom settings app
=> LP-2180 Fixing test method name in custom settings app

requirements/philu/base.txt
[LP-2209](https://philanthropyu.atlassian.net/browse/LP-2209)
- Goto Course Advanced Settings.
- Set `Advanced Module List` as below
`[
"scormxblock"
]`
- Add a new Unit.
- Select Advanced type xblock and click on SCORM.
- goto unit settings upload SCORM package attached in ticket and publish.
=> LP-2209 OTHER Integrate SCORM xblock with edx-platform.

common/djangoapps/student/views/management.py
[LP-1544](https://philanthropyu.atlassian.net/browse/LP-1544)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1392)
=> LP-1544 Remove edx generated emails on email update

lms/envs/common.py, openedx/features/philu_courseware/constants.py, openedx/features/philu_courseware/helpers.py, openedx/features/philu_courseware/models.py, openedx/features/philu_courseware/tests/test_competency_assessment_recording.py, openedx/features/philu_courseware/urls.py, openedx/features/philu_courseware/views.py
[LP-2135](https://philanthropyu.atlassian.net/browse/LP-2135)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1386)
=> LP-2135 Refactor competency assessment APIs

common/djangoapps/philu_commands/management/commands/autoscore_ondemand_course_ora.py, openedx/features/assessment/constants.py, openedx/features/assessment/helpers.py
[LP-1678](https://philanthropyu.atlassian.net/browse/LP-1678) Decrease ORA auto-score from 14 days to 3 days
**Notes**
Unit test are not included because, a separate story will be made to refactor command as per new implementation, due to which all unit test will change.
=> LP-1678 Decrease ORA auto-score from 14 days to 3 days

common/djangoapps/student/tests/factories.py, openedx/features/assessment/tests/constants.py, openedx/features/assessment/tests/factories.py, openedx/features/assessment/tests/test_helpers.py
[LP-2175](https://philanthropyu.atlassian.net/browse/LP-2175)
After discussion with zahid and faraz bhai we decided to not to include unit test for `can_auto_score_ora` in this story as we are expecting major overhaul of that method in [LP-1678](https://philanthropyu.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=LP-1678)
=> LP-2175 Write unit tests for openedx.features.assessment

common/lib/xmodule/xmodule/js/src/capa/display.js
[LP-2162](https://philanthropyu.atlassian.net/browse/LP-2162)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1394)
=> LP-2162 Refactor competency assessment javascript code

common/static/common/templates/notifications/notifications_count.underscore
[LP-1296](https://philanthropyu.atlassian.net/browse/LP-1296)
When notifications counts exceeds 99 then it should be displayed 99+ at LMS side too.
=> LP-1296 Notification icon count bug at LMS

lms/envs/test.py, openedx/features/student_certificates/constants.py, openedx/features/student_certificates/helpers.py, openedx/features/student_certificates/tests/test_helpers.py, openedx/features/student_certificates/tests/test_views.py, openedx/features/student_certificates/views.py, requirements/philu/base.txt, requirements/philu/testing.txt
[LP-2240](https://philanthropyu.atlassian.net/browse/LP-2240)
=> LP-2240 Create and download PDF from certificate image using img2pdf

lms/envs/test.py, openedx/features/student_certificates/constants.py, openedx/features/student_certificates/helpers.py, openedx/features/student_certificates/tests/test_helpers.py, openedx/features/student_certificates/tests/test_views.py, openedx/features/student_certificates/views.py, requirements/philu/base.txt, requirements/philu/testing.txt
[LP-2240](https://philanthropyu.atlassian.net/browse/LP-2240)
=> LP-2240 Create and download PDF from certificate image using img2pdf 

cms/envs/test.py, lms/envs/test.py, pavelib/utils/test/suites/pytest_suite.py, scripts/Jenkinsfiles/python-unittest, scripts/unit-tests.sh
[LP-2136](https://philanthropyu.atlassian.net/browse/LP-2136) Follow up
Previously I added all philu apps, regardless of unit tests for that app exists or not, which seems to be breaking in our pipeline. Now I've removed all those apps which have no unit tests written.
=> Remove unnecessary apps from philu test suit

scripts/all-tests.sh, scripts/clone-theme.sh, scripts/jenkins-common.sh
=> created separate script for clonning theme

openedx/features/philu_courseware/admin.py, openedx/features/philu_courseware/migrations/0004_auto_20200903_0523.py, openedx/features/philu_courseware/models.py
Also added into admin panel
[LP-2264](https://philanthropyu.atlassian.net/browse/LP-2264)
=> LP-2264: Added new model CourseEnrollmentMeta for storing program_uuid

openedx/features/philu_courseware/migrations/0004_auto_20200903_0523.py, openedx/features/philu_courseware/models.py, openedx/features/philu_courseware/tests/factories.py
[LP-2264](https://philanthropyu.atlassian.net/browse/LP-2264)
=> LP-2264: Fixed Null True and Added factory

common/djangoapps/philu_commands/management/commands/tests/test_fetch_course_structures.py
[LP-2243](https://philanthropyu.atlassian.net/browse/LP-2243)
=> LP-2243 Write unit tests for fetch_course_structures philu_command

openedx/features/classrooms/admin.py, openedx/features/classrooms/apps.py, openedx/features/classrooms/models.py, openedx/features/classrooms/tests/tests.py, openedx/features/classrooms/views.py
[LP-2277](https://philanthropyu.atlassian.net/browse/LP-2277)
I have fixed the linting issues related to classrooms application, In which i have added missing doc strings and removed couple of unused imports. 
`
Your code has been rated at 10.00/10 (previous run: 6.30/10, +1.11)
`
=> LP-2277 Fix all linting issues of Classrooms application

common/djangoapps/philu_commands/management/commands/autoscore_ondemand_course_ora.py, common/djangoapps/philu_commands/management/commands/tests/test_autoscore_ondemand_course_ora.py, common/djangoapps/student/tests/factories.py, conftest.py, openedx/features/assessment/constants.py, openedx/features/assessment/helpers.py, openedx/features/assessment/tests/constants.py, openedx/features/assessment/tests/factories.py, openedx/features/assessment/tests/test_helpers.py, openedx/features/philu_utils/constants.py, openedx/features/philu_utils/course.py, openedx/features/philu_utils/tests/mixins.py
**[LP-2303](https://philanthropyu.atlassian.net/browse/LP-2303)** Autoscore ORA command (Unit test only)
**[LP-2294](https://philanthropyu.atlassian.net/browse/LP-2294)** Fix all linting errors for assessment
**Notes**
This PR was reviewed in parts in PR https://github.com/philanthropy-u/edx-platform/pull/1742 (Feature) and in PR https://github.com/philanthropy-u/edx-platform/pull/1754 (unit test and linitng)
=> LP-2303 LP-2294 Autoscore ORA command with linting and unit test

common/djangoapps/philu_commands/management/commands/tests/test_notify_non_active_users.py
[LP-2245](https://philanthropyu.atlassian.net/browse/LP-2245)
=> LP-2245 Write unit tests for notify_non_active_users philu_command

openedx/features/assessment/helpers.py
[LP-2303](https://philanthropyu.atlassian.net/browse/LP-2303) Auto score ORA command
If `AnonymousUserId` model have more than one anonymous user ids against a combination of user and course then do not auto score, to avoid a crash.
=> LP-2303 Handling multiple objects returned by AnonymousUserId

openedx/features/custom_fields/multiselect_with_other/db/fields.py, openedx/features/custom_fields/multiselect_with_other/forms/fields.py, openedx/features/custom_fields/multiselect_with_other/forms/widgets.py
[LP-2295](https://philanthropyu.atlassian.net/browse/LP-2295)
There was a false positive which I had to disable with # pylint: disable=E1101
=> LP-2295 Fix Linting Errors

requirements/philu/base.txt
[LP-2156](https://philanthropyu.atlassian.net/browse/LP-2156)
remove inactive check for inactive user notifications. 
**PR link:** https://github.com/philanthropy-u/edx-notifications/pull/16
**Merge commit link:** https://github.com/philanthropy-u/edx-notifications/commit/c1d538a757f03ea048301f7035713510cc5a1b0d
=> edx_notification repo change commit (remove inactive check for inactive user notifications)

lms/djangoapps/faq/admin.py, lms/djangoapps/onboarding/helpers.py, lms/urls.py, openedx/features/data_extract/admin.py
[LP-2325](https://philanthropyu.atlassian.net/browse/LP-2325)
There are some extra commits in this pull request right now.
=> LP-2325 Remove App Usage

lms/djangoapps/philu_overrides/views.py, openedx/features/cms/helpers.py
[LP-2316](https://philanthropyu.atlassian.net/browse/LP-2316)
- iSort ran on both files
- Unit tests for course_about view will be written in a separate story which is already created and ready for dev
- Linting for views.py file will also be done in a separate linting ticket of philu_overrides, which is also ready for dev
- Unit test related to the change in opendedx/features/cms/helpers.initialize_course_settings is not incorporated, because the pre-written unit test of the initialize_course_settings method is broken. Fixing that unit test would require extra, out-of-scope effort, and hence a separate story will be created for that.
- Linting for the entire cms app is also to be done in a separate linting …
=> LP-2316 Update course detail for mini-lesson

openedx/features/custom_fields/apps.py, openedx/features/custom_fields/multiselect_with_other/constants.py, openedx/features/custom_fields/multiselect_with_other/db/fields.py, openedx/features/custom_fields/multiselect_with_other/forms/fields.py, openedx/features/custom_fields/multiselect_with_other/forms/widgets.py, openedx/features/custom_fields/multiselect_with_other/helpers.py
[LP-2295](https://philanthropyu.atlassian.net/browse/LP-2295)
=> LP-2295 Fix Linting For Custom_Fields

lms/djangoapps/student_dashboard/test/test_views.py, lms/djangoapps/student_dashboard/views.py, openedx/features/course_card/helpers.py
[LP-2178](https://philanthropyu.atlassian.net/browse/LP-2178)
I have removed a few functions from `view.py ` because as per my finding these were dead functions.
- `get_recommended_courses`
- `get_recommended_communities`
Above are the functions I have removed @philanthropy-u/reviewers please counter check if these are safe to remove.
=> LP-2178 OTHER Write all unit test for lms.djangoapps.student_dashboard

lms/djangoapps/student_dashboard/test/test_views.py, lms/djangoapps/student_dashboard/views.py, openedx/features/course_card/helpers.py
LP-2178 OTHER Write all unit test for lms.djangoapps.student_dashboard
[LP-2178](https://philanthropyu.atlassian.net/browse/LP-2178)
=> LP-2178 OTHER Write all unit test for lms.djangoapps.student_dashboard.

openedx/features/badging/__init__.py, openedx/features/badging/admin.py, openedx/features/badging/apps.py, openedx/features/badging/constants.py, openedx/features/badging/handlers.py, openedx/features/badging/helpers.py, openedx/features/badging/helpers/__init__.py, openedx/features/badging/helpers/badges.py, openedx/features/badging/helpers/notifications.py, openedx/features/badging/models.py, openedx/features/badging/tabs.py, openedx/features/badging/tasks.py, openedx/features/badging/templatetags/badge_progress.py, openedx/features/badging/tests/factories.py, openedx/features/badging/tests/test_assign_missing_badges.py, openedx/features/badging/tests/test_handlers.py, openedx/features/badging/tests/test_helpers.py, openedx/features/badging/tests/test_model_badge.py, openedx/features/badging/tests/test_model_userbadge.py, openedx/features/badging/tests/test_tasks.py, openedx/features/badging/tests/test_views.py, openedx/features/badging/urls.py, openedx/features/badging/views.py
[LP-2275](https://philanthropyu.atlassian.net/browse/LP-2275)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1420)
=> LP-2275 Fix linting issues in badging app

common/djangoapps/custom_settings/models.py, openedx/features/course_card/views.py
[LP-2155](https://philanthropyu.atlassian.net/browse/LP-2155)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1422)
=> LP-2155 Add is_mini_lesson method to add mini lesson header on course card

lms/djangoapps/philu_overrides/constants.py, lms/djangoapps/philu_overrides/context_processor.py, lms/djangoapps/philu_overrides/helpers.py, lms/djangoapps/philu_overrides/tests/test_context_processor.py, requirements/philu/base.txt, requirements/philu/testing.txt
=> back merge 

cms/envs/common.py
[LP-2254](https://philanthropyu.atlassian.net/browse/LP-2254)
This is a postfix to resolve an issue that occurs upon running CMS.
=> LP-2254 Postfix import cdn_link in cms

openedx/features/assessment/helpers.py, openedx/features/assessment/tests/test_helpers.py
[LP-2359](https://philanthropyu.atlassian.net/browse/LP-2359) Allow learner and peers to complete remaining ORA steps, once ORA is auto scored
Unit test are updated and all unit test are passing
=> LP-2359 Allow learner and peers to complete remaining ORA steps, once ORA is auto scored

.github/workflows/quality.yml, philu_actions/scripts/dependency_downloader.sh, requirements/edx/base.txt, requirements/edx/testing.txt, requirements/philu/base.txt, requirements/philu/testing.txt
[LP-2382](https://philanthropyu.atlassian.net/browse/LP-2382) Creating Github actions workflow for pylint and iSort
- Once this PR is merged into develop, any PR made to be merged in develop branch will trigger this Github action (build).
- Any push or update in that PR will also trigger Github action (build).
- Same is the case for master, when this PR will merge in master.
- Only python files in PR will be checked, in Github action.
Improvements for future:
- Add cache for OS dependencies and Django requirements
- Update bot messaging and apply tools only to git diff lines instead of git diff files
=> LP-2382 Implement Github actions pipeline for linting

openedx/features/course_card/admin.py, openedx/features/course_card/apps.py, openedx/features/course_card/helpers.py, openedx/features/course_card/models.py, openedx/features/course_card/tests/helpers.py, openedx/features/course_card/tests/test_admin.py, openedx/features/course_card/tests/test_course_date_views.py, openedx/features/course_card/tests/test_helpers.py, openedx/features/course_card/tests/test_views.py, openedx/features/course_card/urls.py, openedx/features/course_card/views.py
[LP-2282](https://philanthropyu.atlassian.net/browse/LP-2282)
Pylint report:
Your code has been rated at 10.00/10 (previous run: 9.98/10, +0.02)
=> LP-2282  Fix all linting errors for course_card

openedx/features/assessment/helpers.py, openedx/features/assessment/tests/test_helpers.py
[LP-2400](https://philanthropyu.atlassian.net/browse/LP-2400)
=> LP-2400: Fixing site configuration variable issue

openedx/features/course_card/admin.py, openedx/features/course_card/apps.py, openedx/features/course_card/helpers.py, openedx/features/course_card/models.py, openedx/features/course_card/tests/helpers.py, openedx/features/course_card/tests/test_admin.py, openedx/features/course_card/tests/test_course_date_views.py, openedx/features/course_card/tests/test_helpers.py, openedx/features/course_card/tests/test_views.py, openedx/features/course_card/urls.py, openedx/features/course_card/views.py
Reverts philanthropy-u/edx-platform#1795 because that was done by squash and merge
=> Revert "LP-2282  Fix all linting errors for course_card"

openedx/features/course_card/admin.py, openedx/features/course_card/apps.py, openedx/features/course_card/helpers.py, openedx/features/course_card/models.py, openedx/features/course_card/tests/helpers.py, openedx/features/course_card/tests/test_admin.py, openedx/features/course_card/tests/test_course_date_views.py, openedx/features/course_card/tests/test_helpers.py, openedx/features/course_card/tests/test_views.py, openedx/features/course_card/urls.py, openedx/features/course_card/views.py
[LP-2282](https://philanthropyu.atlassian.net/browse/LP-2282)
Pylint report:
Your code has been rated at 10.00/10 (previous run: 9.98/10, +0.02)
=> LP-2282 Fix all linting errors for course_card

openedx/features/assessment/helpers.py, openedx/features/assessment/tests/test_helpers.py
[LP-2400](https://philanthropyu.atlassian.net/browse/LP-2400) Reverting ORA Fixing related to site configuration
=> LP-2400 Reverting ORA fixing related to site configuration

requirements/philu/base.txt
[LP-2392](https://philanthropyu.atlassian.net/browse/LP-2392)
=> Integrate action planning tool xblock.

openedx/features/user_leads/admin.py, openedx/features/user_leads/constants.py, openedx/features/user_leads/helpers.py, openedx/features/user_leads/models.py, openedx/features/user_leads/tests/test_helpers.py
[LP-2293](https://philanthropyu.atlassian.net/browse/LP-2293)
=> LP-2293 Fix linting issues of user_leads

requirements/philu/base.txt
Reverts philanthropy-u/edx-platform#1810
=> Revert "Integrate action planning tool xblock."

openedx/features/philu_utils/backend_storage.py, openedx/features/philu_utils/model_factory.py, openedx/features/philu_utils/py_test.py, openedx/features/philu_utils/tests/test_backend_storage.py, openedx/features/philu_utils/tests/test_model_factory.py, openedx/features/philu_utils/tests/test_utils.py, openedx/features/philu_utils/utils.py, openedx/features/xmodules/constants.py, openedx/features/xmodules/helpers.py, openedx/features/xmodules/tests/test_helpers.py
[LP-2270](https://philanthropyu.atlassian.net/browse/LP-2270)
=> LP-2270 Fix linting issues in xmodules and philu_utils

lms/envs/common.py
[LP-2395](https://philanthropyu.atlassian.net/browse/LP-2395)
=> LP-2395 Add django app to the XBlock to track goals in edx-platform.

.github/workflows/quality.yml, philu_actions/scripts/dependency_downloader.sh
[LP-2384](https://philanthropyu.atlassian.net/browse/LP-2384) Implement pycodestyle reporting in Github actions and fixing issues in Github actions quality job
- Do not run checks on migration files
- Adding check for `pycodestyle`
- Do not download OS dependencies or python requirements, if PR does not have any `.py` file
- Enable **cache** for python requirements, it will **reduce build time** roughly from 8 min to 3 min. Note: OS dependencies are still downloaded/installed at runtime.
=> LP-2384 Implement pycodestyle reporting in Github actions and fixing issues in Github actions quality job

.github/workflows/quality.yml, philu_actions/scripts/dependency_downloader.sh
[LP-2384](https://philanthropyu.atlassian.net/browse/LP-2384) Implement pycodestyle reporting in Github actions and fixing issues in Github actions quality job
- Do not run checks on migration files
- Adding check for `pycodestyle`
- Do not download OS dependencies or python requirements, if PR does not have any `.py` file
- Enable **cache** for python requirements, it will **reduce build time** roughly from 8 min to 3 min. Note: OS dependencies are still downloaded/installed at runtime.
=> LP-2384 Fixing issues in github actions quality job

openedx/features/assessment/helpers.py
[LP-2400](https://philanthropyu.atlassian.net/browse/LP-2400)
=> LP-2400 Autoscore ORA on same day if constant is zero

lms/envs/common.py
[LP-2395](https://philanthropyu.atlassian.net/browse/LP-2395)
=> [LP-2395] Add django app to the XBlock to track goals in edx-platform.

lms/djangoapps/philu_overrides/branding/api.py, lms/djangoapps/philu_overrides/constants.py, lms/djangoapps/philu_overrides/context_processor.py, lms/djangoapps/philu_overrides/courseware/tasks.py, lms/djangoapps/philu_overrides/courseware/views/views.py, lms/djangoapps/philu_overrides/helpers.py, lms/djangoapps/philu_overrides/management/commands/fix_polls_data.py, lms/djangoapps/philu_overrides/philu_third_party_auth/context_processor.py, lms/djangoapps/philu_overrides/philu_third_party_auth/custom_backends.py, lms/djangoapps/philu_overrides/philu_third_party_auth/helpers.py, lms/djangoapps/philu_overrides/tasks.py, lms/djangoapps/philu_overrides/user_api/tests/test_views.py, lms/djangoapps/philu_overrides/user_api/views.py, lms/djangoapps/philu_overrides/views.py
[LP-2280](https://philanthropyu.atlassian.net/browse/LP-LP-2280)
[Theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1427)
=> LP-2280 Fix linting issues in philu_overrides app

openedx/features/cms/constants.py, openedx/features/cms/helpers.py, openedx/features/cms/tests/factories.py, openedx/features/cms/tests/helpers.py, openedx/features/cms/tests/test_helpers.py, openedx/features/cms/tests/test_views.py, openedx/features/cms/urls.py, openedx/features/cms/views.py
[LP-2281](https://philanthropyu.atlassian.net/browse/LP-2281)
Ran isort first and added missing doc-strings for modules and methods.
- `constants.py` added module doc-string
- `helpers.py` added module doc-string
- `tests/factories.py` added module, methods doc-strings
- `tests/helpers.py` added module doc-string removed unused code and fix lambda(deprecated-lambda) expression
- `cms/tests/test_helpers.py` removed unused params and added missing doc-strings
- `tests/test_views.py ` fixed import order
- `cms/urls.py` added missing doc-strings
- `cms/views.py` added missing doc-strings and fixed exception handling pylint issue
Your code has been rated at 10.00/10 (previous run: 10.00/10)
=> LP-2281 Fix all linting errors for openedx/features/cms

openedx/features/cms/constants.py, openedx/features/cms/helpers.py, openedx/features/cms/tests/factories.py, openedx/features/cms/tests/helpers.py, openedx/features/cms/tests/test_helpers.py, openedx/features/cms/tests/test_views.py, openedx/features/cms/urls.py, openedx/features/cms/views.py
[LP-2281](https://philanthropyu.atlassian.net/browse/LP-2281)
Ran isort first and added missing doc-strings for modules and methods.
- `constants.py` added module doc-string
- `helpers.py` added module doc-string
- `tests/factories.py` added module, methods doc-strings
- `tests/helpers.py` added module doc-string removed unused code and fix lambda(deprecated-lambda) expression
- `cms/tests/test_helpers.py` removed unused params and added missing doc-strings
- `tests/test_views.py ` fixed import order
- `cms/urls.py` added missing doc-strings
- `cms/views.py` added missing doc-strings and fixed exception handling pylint issue
Your code has been rated at 10.00/10 (previous run: 10.00/10)
=> LP-2281 Fix all linting errors for openedx/features/cm

lms/envs/common.py, lms/urls.py
[LP-2433](https://philanthropyu.atlassian.net/browse/LP-2433)
=> LP-2433 Integrate msp_dashboard with edx-platform.

cms/envs/common.py
[LP-2393](https://philanthropyu.atlassian.net/browse/LP-2393)
=> LP-2393 OTHER Implement XBlock endpoint for the CRUD operations.

cms/envs/common.py
[LP-2393](https://philanthropyu.atlassian.net/browse/LP-2393)
=> [LP-2393] Integrate msp and action planner with cms. 

common/lib/mandrill_client/client.py
[LP-2410](https://philanthropyu.atlassian.net/browse/LP-2410)
Note:
added a share by email feature to share image of action planner with multiple users
=> LP-2410 Share PDF by Email

cms/envs/common.py, lms/envs/common.py, lms/urls.py
=> back merge

common/lib/mandrill_client/client.py
[LP-2410](https://philanthropyu.atlassian.net/browse/LP-2410)
=> LP-2410 Share PNG by Email

openedx/features/partners/models.py
=> :zap: pylint errors resolve

setup.py
[LP-2437](https://philanthropyu.atlassian.net/browse/LP-2437)
=> LP-2437 🌱 `My Metrics Dashboard` tab in course experience.

common/djangoapps/philu_commands/management/commands/tests/test_auto_generate_certificates_for_open_courses.py
[LP-2197](https://philanthropyu.atlassian.net/browse/LP-2197)
Add test cases for auto generate certificates for open courses
=> test cases for auto generate certificates for open courses

common/djangoapps/philu_commands/management/commands/tests/test_auto_generate_certificates_for_open_courses.py, common/djangoapps/student/views/management.py, common/lib/mandrill_client/client.py
=> back merge with master

openedx/features/job_board/migrations/0006_job_user.py
=> add null and blank to true

openedx/features/job_board/admin.py, openedx/features/job_board/migrations/0006_job_user.py, openedx/features/job_board/models.py
=> :zap: change user migrations

common/lib/discovery_client/client.py, common/lib/surveygizmo_client/client.py
[LP-2268](https://philanthropyu.atlassian.net/browse/LP-2268)
Fixed pylint issues for Survey Gizmo and Discovery Clients.
Violations are listed in the mentioned ticket. Score is 10/10 for now.
=> LP-2268 Survey Gizmo and Discovery Clients Linting

common/lib/discovery_client/client.py, common/lib/surveygizmo_client/client.py
[LP-2268](https://philanthropyu.atlassian.net/browse/LP-2268)
=> LP-2268 Fix all linting errors for three clients in common lib

openedx/features/student_certificates/__init__.py, openedx/features/student_certificates/admin.py, openedx/features/student_certificates/apps.py, openedx/features/student_certificates/constants.py, openedx/features/student_certificates/handlers.py, openedx/features/student_certificates/helpers.py, openedx/features/student_certificates/models.py, openedx/features/student_certificates/signals.py, openedx/features/student_certificates/tasks.py, openedx/features/student_certificates/tests/test_helpers.py, openedx/features/student_certificates/tests/test_views.py, openedx/features/student_certificates/views.py
[LP-2291](https://philanthropyu.atlassian.net/browse/LP-2291)
- Fix pylint issues for the _student_certificates_ application
- Run isort for all the files
6 out 15 tests were failing even prior to the linting changes, kindly ignore those.
=> LP-2291 - Fix linting issues in student_certificates application

openedx/features/student_certificates/__init__.py, openedx/features/student_certificates/admin.py, openedx/features/student_certificates/apps.py, openedx/features/student_certificates/constants.py, openedx/features/student_certificates/handlers.py, openedx/features/student_certificates/helpers.py, openedx/features/student_certificates/models.py, openedx/features/student_certificates/signals.py, openedx/features/student_certificates/tasks.py, openedx/features/student_certificates/tests/test_helpers.py, openedx/features/student_certificates/tests/test_views.py, openedx/features/student_certificates/views.py
[LP-2291](https://philanthropyu.atlassian.net/browse/LP-2291)
- Fix pylint issues for the student_certificates application
- Run isort for all the files
6 out 15 tests were failing even prior to the linting changes, kindly ignore those.
=> LP-2291 - Fix pylint issues in student_certificates application

lms/djangoapps/philu_overrides/branding/api.py, lms/djangoapps/philu_overrides/constants.py, lms/djangoapps/philu_overrides/context_processor.py, lms/djangoapps/philu_overrides/courseware/tasks.py, lms/djangoapps/philu_overrides/courseware/views/views.py, lms/djangoapps/philu_overrides/helpers.py, lms/djangoapps/philu_overrides/management/commands/fix_polls_data.py, lms/djangoapps/philu_overrides/philu_third_party_auth/context_processor.py, lms/djangoapps/philu_overrides/philu_third_party_auth/custom_backends.py, lms/djangoapps/philu_overrides/philu_third_party_auth/helpers.py, lms/djangoapps/philu_overrides/tasks.py, lms/djangoapps/philu_overrides/user_api/tests/test_views.py, lms/djangoapps/philu_overrides/user_api/views.py, lms/djangoapps/philu_overrides/views.py
[LP-2280](https://philanthropyu.atlassian.net/browse/LP-2280)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1439)
=>  LP-2280 Fix linting issues in philu_overrides app

common/djangoapps/mailchimp_pipeline/__init__.py, common/djangoapps/mailchimp_pipeline/apps.py, common/djangoapps/mailchimp_pipeline/client.py, common/djangoapps/mailchimp_pipeline/helpers.py, common/djangoapps/mailchimp_pipeline/signals/handlers.py, common/djangoapps/mailchimp_pipeline/tasks.py, common/djangoapps/mailchimp_pipeline/tests/helpers.py, common/djangoapps/mailchimp_pipeline/tests/test_client.py, common/djangoapps/mailchimp_pipeline/tests/test_signals.py, common/djangoapps/mailchimp_pipeline/tests/test_tasks.py
[LP-2271](https://philanthropyu.atlassian.net/browse/LP-2271)
- Fix all the linting issues of mailchimp_pipeline
- Run isort on all the files
=> LP-2271 - Fix all the linting issues in the mailchimp_pipeline application

lms/djangoapps/teams/views.py
[LP-1829](https://philanthropyu.atlassian.net/browse/LP-1829)
[Nodebb-theme-PR](https://github.com/philanthropy-u/nodebb-theme-philu-community/pull/645)
[Nodebb-badging-PR](https://github.com/philanthropy-u/nodebb-plugin-philu-badging/pull/28)
=> If learners leave a team, remove their badges from that team

.github/workflows/quality.yml
An improvement in Github action for linting
- Post report on PR as a comment on PR, rather than comment on commit in PR
- Update cache invalidation logic
=> An improvement in Github action for linting

lms/djangoapps/philu_overrides/views.py
[LP-816](https://philanthropyu.atlassian.net/browse/LP-816)
=> System displays 404 Error upon clicking on 'If you need further assistance, contact technical assistance'

openedx/features/ondemand_email_preferences/admin.py, openedx/features/ondemand_email_preferences/helpers.py, openedx/features/ondemand_email_preferences/models.py, openedx/features/ondemand_email_preferences/urls.py, openedx/features/ondemand_email_preferences/utils.py, openedx/features/ondemand_email_preferences/views.py
[LP-2296](https://philanthropyu.atlassian.net/browse/LP-2296)
=> LP-2296 Fix all linting errors for ondemand_email_preferences app

lms/djangoapps/philu_overrides/views.py, openedx/features/ondemand_email_preferences/admin.py, openedx/features/ondemand_email_preferences/helpers.py, openedx/features/ondemand_email_preferences/models.py, openedx/features/ondemand_email_preferences/urls.py, openedx/features/ondemand_email_preferences/utils.py, openedx/features/ondemand_email_preferences/views.py
=> Refresh develop from master

openedx/features/student_certificates/views.py
[LP-2578](https://philanthropyu.atlassian.net/browse/LP-2578)
=> Course end date being displayed on 'My Certificates' page

openedx/features/student_certificates/helpers.py
[LP-1750](https://philanthropyu.atlassian.net/browse/LP-1750)
Append login redirect url with program credential for authentication
=> [LP-1750] Append redirect url with program credential for authentication

cms/envs/test.py, lms/envs/test.py, openedx/features/specializations/helpers.py, openedx/features/specializations/tests/factories.py, openedx/features/specializations/tests/mock_get_program_helpers.py, openedx/features/specializations/tests/test_helpers.py, openedx/features/specializations/tests/test_views.py, openedx/features/specializations/urls.py, openedx/features/specializations/views.py, requirements/philu/base.txt
[LP-1744](https://philanthropyu.atlassian.net/browse/LP-1744)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1444)
Notes:
1. Code include all test cases
2. Mocking package `pytest-mock==2.0.0` added to philu base requirement file. I have verified that it does not change version of any other package
=> LP-1744 Enroll all courses of a specialisation on single click 

requirements/edx/base.txt, requirements/edx/development.txt, requirements/edx/testing.txt
[LP-2613](https://philanthropyu.atlassian.net/browse/LP-2613) Fix requirements for py2neo
=> LP-2613 Fix requirements for py2neo

requirements/edx/base.txt, requirements/edx/development.txt, requirements/edx/testing.txt
[LP-2613](https://philanthropyu.atlassian.net/browse/LP-2613) Fix requirements for py2neo
=> LP-2613 Fixing py2neo package issue

lms/djangoapps/homepage/constants.py, lms/djangoapps/homepage/custom_context_processors.py, lms/djangoapps/homepage/tests/test_custom_context_processors.py, lms/djangoapps/homepage/urls.py, lms/djangoapps/student_dashboard/views.py, openedx/features/student_certificates/helpers.py, openedx/features/student_certificates/views.py, requirements/edx/base.txt, requirements/edx/development.txt, requirements/edx/testing.txt
[LP-2276](https://philanthropyu.atlassian.net/browse/LP-2276) Fix all linting issues of homepage and student_dashboard
=> LP-2276 Fix all linting issues of homepage and student_dashboard

openedx/core/djangoapps/programs/utils.py
[LP-2452](https://philanthropyu.atlassian.net/browse/LP-2452)
Added some logging and fix for backword compatibility.
=> LP-2452 :bug: User is unable to get specialisation certificate.

cms/envs/test.py, lms/envs/test.py, openedx/features/specializations/helpers.py, openedx/features/specializations/tests/factories.py, openedx/features/specializations/tests/mock_get_program_helpers.py, openedx/features/specializations/tests/test_helpers.py, openedx/features/specializations/tests/test_views.py, openedx/features/specializations/urls.py, openedx/features/specializations/views.py, requirements/philu/base.txt
[LP-1744](https://philanthropyu.atlassian.net/browse/LP-1744)
[Theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1445)
=> LP-1744 Enroll all courses of a specialization on single click

lms/djangoapps/homepage/constants.py, lms/djangoapps/homepage/custom_context_processors.py, lms/djangoapps/homepage/tests/test_custom_context_processors.py, lms/djangoapps/homepage/urls.py, lms/djangoapps/student_dashboard/views.py
[LP-2276](https://philanthropyu.atlassian.net/browse/LP-2276) Fix all linting issues of homepage and student_dashboard
=> LP-2276 Fix all linting issues of homepage & student_dashboard

openedx/features/specializations/__init__.py, openedx/features/specializations/apps.py, openedx/features/specializations/templatetags/sso_meta_tag.py
[LP-2289](https://philanthropyu.atlassian.net/browse/LP-2289)
=> LP-2289 Fix all linting errors for specializations

openedx/features/philu_courseware/admin.py, openedx/features/philu_courseware/helpers.py, openedx/features/philu_courseware/models.py, openedx/features/philu_courseware/serializers.py, openedx/features/philu_courseware/tests/factories.py, openedx/features/philu_courseware/tests/test_competency_assessment_record_manager.py, openedx/features/philu_courseware/tests/test_competency_assessment_recording.py, openedx/features/philu_courseware/tests/test_helpers.py, openedx/features/philu_courseware/urls.py, openedx/features/philu_courseware/views.py, openedx/features/specializations/__init__.py, openedx/features/specializations/apps.py, openedx/features/specializations/templatetags/sso_meta_tag.py
[LP-2289](https://philanthropyu.atlassian.net/browse/LP-2289) Fix all linting errors for philu_courseware
=> LP-2289 Fix all linting errors for philu_courseware

openedx/features/philu_courseware/serializers.py
[LP-2289](https://philanthropyu.atlassian.net/browse/LP-2289) Adding space after class docstring
=> LP-2287 Adding space after class docstring

openedx/features/philu_courseware/admin.py, openedx/features/philu_courseware/helpers.py, openedx/features/philu_courseware/models.py, openedx/features/philu_courseware/serializers.py, openedx/features/philu_courseware/tests/factories.py, openedx/features/philu_courseware/tests/test_competency_assessment_record_manager.py, openedx/features/philu_courseware/tests/test_competency_assessment_recording.py, openedx/features/philu_courseware/tests/test_helpers.py, openedx/features/philu_courseware/urls.py, openedx/features/philu_courseware/views.py
[LP-2287](https://philanthropyu.atlassian.net/browse/LP-2287)
=> LP-2287 Fix all linting errors for philu_courseware

cms/envs/common.py, lms/envs/common.py, lms/urls.py
[LP-2634](https://philanthropyu.atlassian.net/browse/LP-2634)
=> LP-2634 Transform python package to edx plugin_app.

common/lib/nodebb_client/badges.py, common/lib/nodebb_client/categories.py, common/lib/nodebb_client/client.py, common/lib/nodebb_client/groups.py, common/lib/nodebb_client/users.py
[LP-2274](https://philanthropyu.atlassian.net/browse/LP-2274)
=> [LP-2274] Fix all linting issues of nodebb_client

common/djangoapps/philu_commands/helpers.py, common/djangoapps/philu_commands/management/commands/archive_past_courses_communities.py, common/djangoapps/philu_commands/management/commands/auto_generate_certificates_for_open_courses.py, common/djangoapps/philu_commands/management/commands/create_certificates_image.py, common/djangoapps/philu_commands/management/commands/delete_users_from_mailchimp.py, common/djangoapps/philu_commands/management/commands/fetch_course_structures.py, common/djangoapps/philu_commands/management/commands/generate_verification_keys_for_past_certs.py, common/djangoapps/philu_commands/management/commands/notify_non_active_users.py, common/djangoapps/philu_commands/management/commands/send_ondemand_reminder_emails.py, common/djangoapps/philu_commands/management/commands/send_ondemand_weekly_emails.py, common/djangoapps/philu_commands/management/commands/send_referral_follow_up_email.py, common/djangoapps/philu_commands/management/commands/sync_course_enrollments_with_nodebb.py, common/djangoapps/philu_commands/management/commands/sync_users_with_mailchimp.py, common/djangoapps/philu_commands/management/commands/sync_users_with_nodebb.py, common/djangoapps/philu_commands/management/commands/tests/test_autoscore_ondemand_course_ora.py, common/djangoapps/philu_commands/management/commands/tests/test_create_certificates_image_command.py, common/djangoapps/philu_commands/management/commands/tests/test_mailchimp_commands.py, common/djangoapps/philu_commands/management/commands/tests/test_send_referral_follow_up_emails.py, common/djangoapps/philu_commands/management/commands/tests/test_sync_users_with_nodebb_command.py, common/djangoapps/philu_commands/management/commands/tests/update_org_metrics_test_api.py, common/djangoapps/philu_commands/management/commands/tests/update_org_oef_test_api.py, common/djangoapps/philu_commands/management/commands/update_org_metric_prompts.py, common/djangoapps/philu_commands/management/commands/update_org_oef_prompts.py, common/djangoapps/philu_commands/models.py, common/djangoapps/philu_commands/tests/test_helpers.py
[LP-2272](https://philanthropyu.atlassian.net/browse/LP-2272) Fix all linting issues of philu commands
- All linitng issues fixed
- Failing unit test fixed
=> LP-2272 Fix all linting issues of philu commands

common/djangoapps/philu_commands/management/commands/send_ondemand_weekly_emails.py
[LP-2272](https://philanthropyu.atlassian.net/browse/LP-2272)
=> LP-2272 Fixing email check in send_ondemand_weekly_emails

common/djangoapps/philu_commands/helpers.py, common/djangoapps/philu_commands/management/commands/archive_past_courses_communities.py, common/djangoapps/philu_commands/management/commands/auto_generate_certificates_for_open_courses.py, common/djangoapps/philu_commands/management/commands/create_certificates_image.py, common/djangoapps/philu_commands/management/commands/delete_users_from_mailchimp.py, common/djangoapps/philu_commands/management/commands/fetch_course_structures.py, common/djangoapps/philu_commands/management/commands/generate_verification_keys_for_past_certs.py, common/djangoapps/philu_commands/management/commands/notify_non_active_users.py, common/djangoapps/philu_commands/management/commands/send_ondemand_reminder_emails.py, common/djangoapps/philu_commands/management/commands/send_ondemand_weekly_emails.py, common/djangoapps/philu_commands/management/commands/send_referral_follow_up_email.py, common/djangoapps/philu_commands/management/commands/sync_course_enrollments_with_nodebb.py, common/djangoapps/philu_commands/management/commands/sync_users_with_mailchimp.py, common/djangoapps/philu_commands/management/commands/sync_users_with_nodebb.py, common/djangoapps/philu_commands/management/commands/tests/test_autoscore_ondemand_course_ora.py, common/djangoapps/philu_commands/management/commands/tests/test_create_certificates_image_command.py, common/djangoapps/philu_commands/management/commands/tests/test_mailchimp_commands.py, common/djangoapps/philu_commands/management/commands/tests/test_send_referral_follow_up_emails.py, common/djangoapps/philu_commands/management/commands/tests/test_sync_users_with_nodebb_command.py, common/djangoapps/philu_commands/management/commands/tests/update_org_metrics_test_api.py, common/djangoapps/philu_commands/management/commands/tests/update_org_oef_test_api.py, common/djangoapps/philu_commands/management/commands/update_org_metric_prompts.py, common/djangoapps/philu_commands/management/commands/update_org_oef_prompts.py, common/djangoapps/philu_commands/models.py, common/djangoapps/philu_commands/tests/test_helpers.py
[LP-2272](https://philanthropyu.atlassian.net/browse/LP-2272) Fix all linting issues of philu_commands
=> LP-2272 Fix all linting issues of philu_commands

.github/workflows/quality.yml, openedx/features/idea/models.py
[LP-2310](https://philanthropyu.atlassian.net/browse/LP-2310) Fix Github action for quality
=> LP-2310 Fix Github action for quality

.github/workflows/quality.yml, openedx/features/idea/models.py
[LP-2310](https://philanthropyu.atlassian.net/browse/LP-2310) Fixing isort in Github action for quality
=> LP-2310 Fixing isort in Github action for quality

lms/djangoapps/homepage/urls.py
[LP-3004](https://philanthropyu.atlassian.net/browse/LP-3004)
Redirect from lms landing to wordpress site landing page
=> LP-3004 Redirect from lms landing to wordpress site landing page

common/lib/nodebb_client/client.py
[LP-3007](https://philanthropyu.atlassian.net/browse/LP-3007)
=> LP-3007 Fix NodeBB client

lms/djangoapps/philu_overrides/branding/api.py, openedx/features/course_card/views.py
[LP-3008](https://philanthropyu.atlassian.net/browse/LP-3008)
=> LP-3008 Update Course Catalog and Footer

lms/djangoapps/philu_overrides/branding/api.py, openedx/features/course_card/views.py
[LP-3008](https://philanthropyu.atlassian.net/browse/LP-3008)
=> LP-3008 Update Course Catalog & Footer

lms/djangoapps/philu_overrides/branding/api.py
[LP-3008](https://philanthropyu.atlassian.net/browse/LP-3008)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1455)
=> LP-3008 Add URLs for Header and Footer

lms/djangoapps/philu_overrides/branding/api.py
[LP-3013](https://philanthropyu.atlassian.net/browse/LP-3013)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1460)
Update URLs to PhilU static site
=> LP-3013 Update URLs to PhilU static site

lms/djangoapps/philu_overrides/branding/api.py
[LP-3014](https://philanthropyu.atlassian.net/browse/LP-3014)
Redirect Footer FAQ to support site.
=> LP-3014 Redirect Footer FAQ link to support site

lms/djangoapps/philu_overrides/branding/api.py
[LP-3015](https://philanthropyu.atlassian.net/browse/LP-3015)
Update footer link for visitors
=> LP-3015 Update footer link for visitors

lms/djangoapps/onboarding/helpers.py
[LP-3022](https://philanthropyu.atlassian.net/browse/LP-3022)
=> LP-3022 Fix Template Id for Change Email Alert

common/lib/hubspot_client/helpers.py, common/lib/hubspot_client/tasks.py
[LP-3025](https://philanthropyu.atlassian.net/browse/LP-3025)
=> LP-3025 Fix profile country field error
