lms/djangoapps/courseware/views/views.py

If course is not started yet then user will be redirected to course about page after enrollment.

Redirection to course about page for future courses

---

lms/djangoapps/philu_overrides/courseware/views/views.py
openedx/core/djangoapps/timed_notification/core.py

This should fix the missing `org` at the end of **certificate_url**

Fix: fix LMS_ROOT_URL

---

openedx/core/lib/log_utils.py
openedx/core/lib/logsettings.py

Polling is create that logging numerous times per second which is quite headache to track the logs.
`2018-07-02 09:02:22,719 INFO 28449 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): local.philanthropyu.org`

remove recurring polling logs filter

---

lms/djangoapps/philu_overrides/views.py
openedx/features/course_card/views.py

The course card will be created but will not be visible. It will be visible only when a learner is enrolled into the course; then the learner would be able to see the course on the catalog and on their dashboard (in ‘Enrolled' tab), and also in ’Past courses' tab when the private course ends. But anyone other than the invited learner will not be able to view the card.

LP-1022 : Ability to create a private course (missing requirement)

---

lms/djangoapps/onboarding/models.py
lms/djangoapps/philu_overrides/user_api/views.py

encoded first_name and last_name strings while being concatenated for the model UserProfile's name field.
removed string typecast on the other field in the UserExtendedProfile Model

LP-1216 Allowed accented characters in fields not being accepted

---

lms/djangoapps/teams/static/teams/templates/team-member.underscore

edx-platform/lms/djangoapps/teams/static/teams/templates/team-member.underscore:3
Change reason because we cant take backbone files to philu-edx-theme and path isnt resolved if we put just the underscore files in the theme

added target _blank into team profile view

---

common/djangoapps/course_modes/views.py
lms/djangoapps/courseware/views/views.py
lms/djangoapps/philu_overrides/helpers.py
lms/djangoapps/philu_overrides/views.py
openedx/core/djangoapps/timed_notification/core.py
openedx/features/student_certificates/views.py

**Description**
Ironwood Combines all of the broken out student views in `__init__.py` of `student.views` . So I created this PR to change relevant imports.

Change imports of student app views according to structure change

---

openedx/features/cms/helpers.py
openedx/features/course_card/helpers.py
openedx/features/course_card/tests/test_helpers.py

[LP-1503](https://philanthropyu.atlassian.net/browse/LP-1503)
Added method set_rerun_schedule_dates to set schedule dates,
Added method set_advanced_settings_due_date to set due_date,
moved method initialze_course_settings from course_card to features/cms/helpers
added flag to set custom_settings course open date in initialize_course_settings_method
fixed case where date had no timezone in delta computation

[LP-1503] Backend Implementation of setting course dates based on course start date

---

common/djangoapps/mailchimp_pipeline/signals/handlers.py
common/lib/mandrill_client/client.py
lms/djangoapps/onboarding/handlers.py
lms/djangoapps/onboarding/helpers.py

- Allow registered learners to change their email address - Part 1: Backend implementation
- This PR allow admin to change email in NodeBB, Mailchimp and sends email to old and new emails
Note: This PR has a corresponding [PR-517](https://github.com/philanthropy-u/nodebb-theme-philu-community/pull/517) in NodeBB theme

LP-1099 Change email in NodeBB, Mailchimp when admin updates it

---

openedx/core/djangoapps/user_api/api.py

Philu requires password even in case of registration using third party auth providers

Remove hide password field code in third party auth registration form

---

common/djangoapps/student/migrations/0009_auto_20170111_0422.py
common/djangoapps/student/migrations/0016_historicaluserprofile.py

Reordering student migration dependencies to fix migration issues
**Context:**
When migration was run on ironwood with ficus dev databases, this was the one of the three issues encounter. `0016_historicaluserprofile` and `0017_auto_20171219_0925` are migrations which were already executed on ficus but after ironwood upgraded, dependence of `0016_historicaluserprofile` automatically changed to `0019_auto_20181221_0540`. Migration 0019 is new, so an already executed migration cannot have dependence on migration which is not yet executed, hence the error. 
**Fix:**
Moving `0016_historicaluserprofile` and `0017_auto_20171219_0925` above in dependency chain. These migrations will execute after `0008_auto_20161117_1209` and before `0009_auto_20170111_0422`.

Reordering student migration dependencies to fix migration issues

---

common/djangoapps/student/urls.py

**Context:**
Ironwood has introduced new flow for LMS user activation, though kept old (Ficus) flow for CMS. Old  activation flow should be restored
**Fix:**
Referred URL to old activation flow (which ironwood use for CMS) instead of new flow

Fixing user account activation flow

---

lms/djangoapps/onboarding/constants.py
lms/djangoapps/philu_api/urls.py
lms/djangoapps/philu_api/views.py
lms/djangoapps/philu_overrides/constants.py
lms/djangoapps/philu_overrides/context_processor.py

**Problem**: Add "Resend Activation Email" button to site banner
**Solution**:
1. **`views.py`**: Added a view named `resend_activation_email` which takes in the request, checks if the user has already been activated (to contain any abuse of the endpoint), and if the user has not been activated, resends the activation email using the pre-existing `reactivation_email_for_user_custom` method from `philu_overrides.helpers`. At the end it sends back an appropriate response to the AJAX call from the front-end.
2. **`urls.py`**: Imported the `resend_activation_email` view and assigned it to a new url pattern: `{lms}/philu/api/resend_activation_email/`.
3. **`context_processor.py`**: Updated the `get_global_alert_messages` method in case of an activation email banner using the constants defined …

mabdullahz/LP-1619: Add "Resend Activation Email" button to site banner

---

lms/djangoapps/grades/models.py

replaced brl.hash_value with brl in bulk_get_or_create because it calls bulk_create afterwards and bulk_create uses objects to create VisibleBlocks whereas brl.hash_value would return a string

[LP-1630] Fixed exception in VisibleBlocks.bulk_create due to incorrect argument passed

---

lms/djangoapps/philu_api/views.py
lms/djangoapps/philu_overrides/constants.py
lms/djangoapps/philu_overrides/context_processor.py

**Problem**: Resend activation email button was enabled on LMS side, but had to be separately enabled in NodeBB
**Resolution**: 
1. **`views.py`**: `csrf_exempt` decorator was used since the django requires that the token is sent in request headers. The request from NodeBB falls under CORS request and hence, that requests is forbidden at edX side. Also, the `user_id` is now being sent in body of the request from both the sides. 
2. **`constants.py`**: `user id` is being sent as a data attribute to edX side to be sent in AJAX request body.
3.  **`context_processor.py`**: `user id` inserted in the alert format-able string to be used by AJAX request

mabdullahz/LP-1631 [BUG]: "Resend Activation Email" option is not available on Community side

---

lms/djangoapps/certificates/views/webview.py
lms/djangoapps/philu_overrides/certificates/webview.py
openedx/features/student_certificates/constants.py
openedx/features/student_certificates/helpers.py
openedx/features/student_certificates/urls.py
openedx/features/student_certificates/views.py
requirements/philu/base.txt

- Create download/save as PDF functionality for certificates
- Django admin template for certificate is updated. See [PR-958](https://github.com/philanthropy-u/philu-edx-theme/pull/958) in theme
- [pdfkit](https://pypi.org/project/pdfkit/) dependency added
- [wkhtmltopdf](https://wkhtmltopdf.org/) version **0.12.5** installed in virtual environment, it is pre-requisite for pdfkit

LP-872 Creating PDF certificate

---

openedx/features/partners/g2a/constants.py
openedx/features/partners/g2a/forms.py
openedx/features/partners/g2a/views.py
openedx/features/partners/urls.py
openedx/features/partners/views.py

- Implement Registration for new users (Full name, email, password)
- Populate other mandatory (yet hidden) fields automatically
- Auto-activate these users (if it only requires active flag to be set as true)
- Associate these users with the “Give2Asia” organization
- Create a bridge table between user and partner table
**Steps to test code:**
1. Create partner in Django admin
2. Make one user (on platform) admin of that partner (organization), in this case Give2Asia
3. Partner label in Django admin must match exactly to organization name in platform
4. Register new user through partner's registration API

LP-1637 G2A RegFlow: User Registration Implementation

---

lms/djangoapps/grades/models.py

The underlying exception was occurring:
```
Traceback (most recent call last):
File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/index.py", line 153, in get
return self.render(request)
File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/index.py", line 217, in render
return render_to_response('courseware/courseware.html', self._create_courseware_context(request))
File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 169, in render_to_response
return HttpResponse(render_to_string(template_name, dictionary, namespace, request), **kwargs)
File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 159, in render_to_string
return template.render(dictionary, request)
File …
```

[LP-1630] Fixed case of circular dependency between VisibleBlocks and PersistentSubsectionGrade

---

common/djangoapps/philu_commands/management/commands/auto_generate_certificates_for_open_courses.py

[FIX] TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'

LP-1674 OTHER Send emails to prompt learners to view & download

---

common/djangoapps/nodebb/signals/handlers.py
openedx/features/badging/constants.py
openedx/features/badging/models.py

[LP-1707](https://philanthropyu.atlassian.net/browse/LP-1707)
Handle badge assignment edge cases in course team
Second part of AC does not need dev work. When user un-enroll from course, his record in `CourseTeamMembership` remains intact hence he can get team badges

LP-1707 Handling badging edge cases for team

---

lms/djangoapps/philu_overrides/views.py

[LP-1729](https://philanthropyu.atlassian.net/browse/LP-1729)
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1097)
Since edX uses the Logistration view, to handle both login and registration, moving to the pop up based registration flow, we need to call a separate custom made template in case of registration. These changes cater to those.

mabdullahz/LP-1729: fix login

---

openedx/features/partners/models.py

[LP-1902](https://philanthropyu.atlassian.net/browse/LP-1902)
When adding a partner in admin, the default JSON configuration field had single quotes in it, which was invalid JSON. Fixed it by wrapping the default dict in json.dumps

[FIX] mabdullahz/LP-1902: Fixed the JSON field single quotes error

---

lms/djangoapps/onboarding/admin.py
openedx/features/ondemand_email_preferences/admin.py
openedx/features/partners/admin.py
openedx/features/philu_courseware/admin.py
openedx/features/user_leads/admin.py

Please highlight any django model (which has relation to user model) which is frequently used by philu admin but is not fixed in this PR so that we can fix those model admins as well. 
**Fix Reference:**
https://books.agiliq.com/projects/django-admin-cookbook/en/latest/many_fks.html#how-to-manage-a-model-with-a-fk-with-a-large-number-of-objects
This link has visuals of admin site after the fix.

Fix timeout issue in admin site when loading large number of users

---

openedx/custom/forms/fields.py

[LP-2014](https://philanthropyu.atlassian.net/browse/LP-2014)
"Other" field in all the questions is not accepting 50 characters. It is accepting less than 50 characters.
Improper validation message is displaying if the maximum allowed length is violated for Other field.

LP-2014 Fix other field max length and error message

---

lms/djangoapps/teams/search_indexes.py

[LP-1977](https://philanthropyu.atlassian.net/browse/LP-1977)
Disconnecting the receiver because during investigation on LP-1977 we came to know that indexing team on elastic search is taking about 40 seconds and Philu is not using this index(elastic) at all.
Merging directly into master because we've to push the release to test this hypothesis that disconnecting teams from elastic search will fix the issue.

LP-1977 Stop indexing of teams on elastic search

---

lms/urls.py

[LP-1868](https://philanthropyu.atlassian.net/browse/LP-1868) Configuration of CloudSponge with our platform
[philu-edx-theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1244)
In order to configure provider apps with CloudSponge we need to create a static page that can act as a proxy URL. This proxy URL will be added to the configuration of all providers i.e. Google, Microsoft, and Yahoo.
The proxy URL will be `{base_url}/auth/proxy/cloudsponge`

LP-1868 Create proxy url for CloudSponge configuration

---

openedx/features/user_leads/helpers.py
openedx/features/user_leads/tests/test_helpers.py

[LP-2066](https://philanthropyu.atlassian.net/browse/LP-2066)
Earlier we were using `get_or_create` method to save a UTM if it did not already exist. But it was breaking because we were passing it `utm_params` in parameters which do not work because only `user` and `origin` are defined as `unique_together` in the model. Passing it `utm_params` does not return the existing entry, which causes an `IntegrityError`.

[POSTFIX] LP-2066: Update the `save_user_utm` method and tests for not checking against UTMs

---

openedx/features/partners/tests/test_views.py

[LP-2030](https://philanthropyu.atlassian.net/browse/LP-2030)
There were a few unit tests broken for views in the partners app. 
1. One test was failing because the theme was not set and template was not found. Used the helper `configure_philu_theme` recently introduced to fix that.
2. Other unit tests were failing because of a recent change in the partner registration form, where the country drop down was changed to send the country key instead of the country value. Changed the country value used in unit tests to country key, and those started working.

LP-2030: Fix partners broken unit tests for views

---

cms/static/js/index.js
cms/static/js/models/uploads.js
cms/static/js/views/edit_chapter.js

[LP-2095](https://philanthropyu.atlassian.net/browse/LP-2095)
Applied the security [patch1](https://discuss.openedx.org/t/security-patch-for-xss-issue/2061) and [patch2](discuss.openedx.org/t/security-patch-for-edit-chapter-xss-lint-issues/2030) for xss issue. Please visit the security patch link for more details on why this was required.
1. **Changes made by the patch**: 
- Use of `edx.HtmlUtils.HTML` when displaying the error in a `<p>` tag to avoid the execution of any malicious script trying to execute. This change has been made in two places inside the `cms/static/js/index.js` file, in `CreateCourseUtils.create` and `CreateLibraryUtils.create` methods.
- Use of backbone `<%-` tag which escapes any HTML from the given value instead of `<%=` in `cms/static/js/models/uploads.js`
2. …

LP-2095: Apply library and uploads XSS patch

---

common/djangoapps/mailchimp_pipeline/tests/helpers.py
common/djangoapps/mailchimp_pipeline/tests/test_signals.py
common/djangoapps/mailchimp_pipeline/tests/test_tasks.py
lms/djangoapps/onboarding/tests/factories.py

[LP-2114](https://philanthropyu.atlassian.net/browse/LP-2114) Fixing Mailchimp broken unit tests
1. There were two issue with tests
- Task `update_org_details_at_mailchimp` have now 4 param, and in unit test it was not updated, so it was taking only 3 params
- The max length of organization's `org_type` is up to 10 characters, but for unit test data `org_type` was provided of more than 10 characters long
2. All 27 test in `djangoapps/mailchimp_pipeline` passed

LP-2114 Fixing mailchimp broken unit tests

---

openedx/core/djangoapps/user_authn/views/register.py

[LP-2022](https://philanthropyu.atlassian.net/browse/LP-2022) Registration flow gets stuck if a user adds accented character like "é" in first name and last name field.
This is a core change, but change is already logged, since this is our line of code.

LP-2022 Fixing registration and allow name with accented character

---

openedx/features/philu_courseware/helpers.py
openedx/features/philu_courseware/models.py
openedx/features/philu_courseware/serializers.py
openedx/features/philu_courseware/tests/factories.py
openedx/features/philu_courseware/tests/test_competency_assessment_record_manager.py
openedx/features/philu_courseware/tests/test_helpers.py
openedx/features/philu_courseware/urls.py
openedx/features/philu_courseware/views.py

[LP-2161](https://philanthropyu.atlassian.net/browse/LP-2161)
- First you need to setup a competency assessment. 
- Attempt post assessment.
- Hit following endpoint with required data to revert post assessment attempts.
```
{base_url}/api/courses/{course_id}/courseware/revert_user_post_assessment_attempts/
```
This is POST api which needs following data
```
{
"problem_id": "block-v1:Arbisoft+CA101+2020_CA+type@problem+block@23c2935e351da7e00fbd"
}
```

LP-2161 Add revert user post assessment attempts API

---

common/djangoapps/custom_settings/models.py
common/djangoapps/custom_settings/signals/handlers.py
common/djangoapps/custom_settings/tests/factories.py
common/djangoapps/custom_settings/tests/test_handlers.py
common/djangoapps/custom_settings/tests/test_helpers.py
common/djangoapps/custom_settings/tests/test_models.py
common/djangoapps/custom_settings/tests/test_views.py
openedx/features/partners/tests/factories.py
openedx/features/partners/tests/test_helpers.py
openedx/features/philu_utils/model_factory.py
openedx/features/philu_utils/py_test.py
openedx/features/philu_utils/tests/test_model_factory.py

[LP-2180](https://philanthropyu.atlassian.net/browse/LP-2180) Unit test for custom settings app
- All unit test for the app included
- A factory for custom settings model was created in partners app, which is moved from there to custom_settings app
- All test for partners app passing

LP-2180 Unit test for custom settings app

---

openedx/features/teams/decorators.py
openedx/features/teams/helpers.py
openedx/features/teams/mixins.py
openedx/features/teams/serializers.py
openedx/features/teams/tests/factories.py
openedx/features/teams/tests/test_helpers.py
openedx/features/teams/tests/test_serializers.py
openedx/features/teams/tests/test_views.py
openedx/features/teams/urls.py
openedx/features/teams/views.py

[LP-2292](https://philanthropyu.atlassian.net/browse/LP-2292) Fix all linting errors for openedx/features/teams
```
************* Module edx-platform.openedx.features.teams.mixins
C:  1, 0: Missing module docstring (missing-docstring)
C:  5, 0: First line empty in class docstring (docstring-first-line-empty)
************* Module edx-platform.openedx.features.teams.serializers
C: 12, 0: First line empty in class docstring (docstring-first-line-empty)
C: 17, 4: First line empty in method docstring (docstring-first-line-empty)
C: 38, 0: First line empty in class docstring (docstring-first-line-empty)
C: 45, 4: First line empty in method docstring (docstring-first-line-empty)
W: 45, 4: Parameters differ from overridden 'to_representation' method (arguments-differ)
C: 51, 4: First line empty …
```

LP-2292 Fixing all linting issues for openedx teams app

---

openedx/features/teams/decorators.py
openedx/features/teams/helpers.py
openedx/features/teams/mixins.py
openedx/features/teams/serializers.py
openedx/features/teams/tests/factories.py
openedx/features/teams/tests/test_helpers.py
openedx/features/teams/tests/test_serializers.py
openedx/features/teams/tests/test_views.py
openedx/features/teams/urls.py
openedx/features/teams/views.py

[LP-2292](https://philanthropyu.atlassian.net/browse/LP-2292) Fix all linting errors for openedx/features/teams
```
************* Module edx-platform.openedx.features.teams.mixins
C:  1, 0: Missing module docstring (missing-docstring)
C:  5, 0: First line empty in class docstring (docstring-first-line-empty)
************* Module edx-platform.openedx.features.teams.serializers
C: 12, 0: First line empty in class docstring (docstring-first-line-empty)
C: 17, 4: First line empty in method docstring (docstring-first-line-empty)
C: 38, 0: First line empty in class docstring (docstring-first-line-empty)
C: 45, 4: First line empty in method docstring (docstring-first-line-empty)
W: 45, 4: Parameters differ from overridden 'to_representation' method (arguments-differ)
C: 51, 4: First line empty …
```

LP-2292 Fixing all linting issues for teams app

---

common/static/common/templates/notifications/notifications_count.underscore

[LP-1296](https://philanthropyu.atlassian.net/browse/LP-1296)
When notifications counts exceeds 99 then it should be displayed 99+ at LMS side too.

LP-1296 Notification icon count bug at LMS

---

cms/envs/test.py
lms/envs/test.py
pavelib/utils/test/suites/pytest_suite.py
scripts/Jenkinsfiles/python-unittest
scripts/unit-tests.sh

- Add MANDRILL_API_KEY in credentials and pick up from environment
Previously I added all philu apps, regardless of unit tests for that app exists or not, which seems to be breaking in our pipeline. Now I've removed all those apps which have no unit tests written.

Remove out xmodules from pipline

---

lms/djangoapps/philu_api/helpers.py
lms/djangoapps/philu_api/tests/test_views.py
lms/djangoapps/philu_api/urls.py
lms/djangoapps/philu_api/views.py
openedx/features/student_certificates/helpers.py

[LP-2279](https://philanthropyu.atlassian.net/browse/LP-2279)
I have suppressed borad-except warning from pylint on couple of places. The reason being they were placed there to catch all exceptions and logged the errors. As per pep8
** A good rule of thumb is to limit use of bare 'except' clauses to two cases:
1. If the exception handler will be printing out or logging the traceback; at least the user will be aware that an error has occurred.
2. If the code needs to do some cleanup work, but then lets the exception propagate upwards with raise. try...finally can be a better way to handle this case.
```
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

LP-2279 Fix all linting issues of philu_api

---

openedx/features/custom_fields/apps.py
openedx/features/custom_fields/multiselect_with_other/constants.py
openedx/features/custom_fields/multiselect_with_other/db/fields.py
openedx/features/custom_fields/multiselect_with_other/forms/fields.py
openedx/features/custom_fields/multiselect_with_other/forms/widgets.py
openedx/features/custom_fields/multiselect_with_other/helpers.py

[LP-2295](https://philanthropyu.atlassian.net/browse/LP-2295)
************* Module edx-platform.openedx.features.custom_fields.apps
C:  1, 0: Missing module docstring (missing-docstring)
************* Module edx-platform.openedx.features.custom_fields.multiselect_with_other.constants
C:  1, 0: Missing module docstring (missing-docstring)
************* Module edx-platform.openedx.features.custom_fields.multiselect_with_other.helpers
C:  1, 0: Missing module docstring (missing-docstring)
C:  4, 0: Missing function docstring (missing-docstring)
W: 22, 0: "choices, value" missing in parameter type documentation (missing-type-doc)
W: 22, 0: Missing return type documentation (missing-return-type-doc)
W: 34, 0: "values" missing in parameter type documentation (missing-type-doc)
W: 34, 0: Missing …

LP-2295 Fix Linting Custom_Fields

---

openedx/features/assessment/helpers.py
openedx/features/assessment/tests/test_helpers.py
openedx/features/philu_utils/utils.py

[LP-2303](https://philanthropyu.atlassian.net/browse/LP-2303) Auto score ORA command
**Notes**
It was assumed that method `get_rubric_from_ora` was getting `usage_key` param as an object, but in actual `usage_key` was passed as a string. Though, in unit tests, `get_rubric_from_ora` method was getting `usage_key` as object, which is why unit-tests were passing.
So, now `usage_key` string is converted to object explicitly, inside `get_rubric_from_ora` method, and unit tests are updated accordingly.

LP-2303 Fixing inconsistent usage_key in ORA command

---

openedx/features/assessment/constants.py
openedx/features/assessment/helpers.py
openedx/features/assessment/tests/test_helpers.py

[LP-2303](https://philanthropyu.atlassian.net/browse/LP-2303) ORA auto score command
The delta calculated from current DateTime and ORA number of day to wait was taken as date (instead of DateTime) and was compared to the date value of `created_at`. It was working fine on local but was not working on the dev server.
Now all dates `delta` and `crrated_at` are compared as UTC DateTime. This works on both servers, local and dev.
- Unit test updated
- All unit test are passing

LP-2303 Fixing datetime inconsistency in delta and created at

---

common/djangoapps/custom_settings/__init__.py
common/djangoapps/custom_settings/admin.py
common/djangoapps/custom_settings/apps.py
common/djangoapps/custom_settings/helpers.py
common/djangoapps/custom_settings/models.py
common/djangoapps/custom_settings/signals/handlers.py
common/djangoapps/custom_settings/tests/factories.py
common/djangoapps/custom_settings/tests/test_handlers.py
common/djangoapps/custom_settings/tests/test_helpers.py
common/djangoapps/custom_settings/tests/test_models.py
common/djangoapps/custom_settings/tests/test_views.py
common/djangoapps/custom_settings/urls.py
common/djangoapps/custom_settings/views.py

[LP-2273](https://philanthropyu.atlassian.net/browse/LP-2273)
Following issue are fixed
```
************* Module edx-platform.common.djangoapps.custom_settings
common/djangoapps/custom_settings/__init__.py:1: [C0111(missing-docstring), ] Missing module docstring
************* Module edx-platform.common.djangoapps.custom_settings.models
common/djangoapps/custom_settings/models.py:1: [C0111(missing-docstring), ] Missing module docstring
common/djangoapps/custom_settings/models.py:29: [W0221(arguments-differ), CustomSettings.save] Parameters differ from overridden 'save' method
************* Module edx-platform.common.djangoapps.custom_settings.apps
common/djangoapps/custom_settings/apps.py:1: [C0111(missing-docstring), ] Missing module docstring
common/djangoapps/custom_settings/apps.py:11: …
```

LP-2273 Fixing linting issues in custom settings

---

common/djangoapps/custom_settings/models.py
openedx/features/course_card/views.py

[LP-2155](https://philanthropyu.atlassian.net/browse/LP-2155)
[Theme PR](https://github.com/philanthropy-u/philu-edx-theme/pull/1419)

 LP-2155 Add is_mini_lesson method to add mini lesson header on course card

---

lms/djangoapps/philu_overrides/constants.py
lms/djangoapps/philu_overrides/context_processor.py
lms/djangoapps/philu_overrides/helpers.py
lms/djangoapps/philu_overrides/tests/test_context_processor.py
requirements/philu/base.txt
requirements/philu/testing.txt

[LP-2254](https://philanthropyu.atlassian.net/browse/LP-2254)
This PR contains pytests and hence pylint produced some unexpected warnings, which had to be suppresed.
- After the `request_object` fixture prototype in test_context_processor.py, I have suppressed the pylint warning: `unused-argument`. `db` is not explicitly used in `request_object` and thus pylint gives a warning, but it must be passed as a fixture, otherwise database access is not allowed inside the `request_object` method.
- After every test method argument of `request_object`, I have suppressed the following pylint warning: `redefined-outer-name`. `request_object` is to be passed as a fixture to the test methods so that the methods can access the request object. Maybe pylint is not mature enough to recognize fixture …

LP-2254 philu_overrides.context_processor unit tests

---

requirements/philu/base.txt

[LP-2254](https://philanthropyu.atlassian.net/browse/LP-2254)
Removing the new package `pytest-mock==2.0.0` introduced in base.txt. After the package was introduced, it has probably updated other packages, due to which deployment is failing on dev server.

LP-2254 Postfix remove pytest-mock from base.txt

---

common/djangoapps/philu_commands/management/commands/tests/test_archive_past_courses_communities_command.py

[LP-2196](https://philanthropyu.atlassian.net/browse/LP-2196)
Written unit tests Unit Tests for Django management command to archive course community on nodeBB.
which contains the following tests.
- `test_archive_command_with_past_courses`
- `test_archive_command_without_courses`
- `test_archive_command_with_no_past_courses`
- `test_archive_command_with_one_past_courses`
**Note:**
These changes also contains isort and linting related issues fixes.

LP-2196 Write unit tests for Command archive_past_courses_communities 

---

common/djangoapps/philu_commands/management/commands/tests/test_archive_past_courses_communities_command.py

[LP-2196](https://philanthropyu.atlassian.net/browse/LP-2196)
Written unit tests Unit Tests for Django management command to archive course community on nodeBB.
which contains the following tests.
- `test_archive_command_with_past_courses`
- `test_archive_command_without_courses`
- `test_archive_command_with_no_past_courses`
- `test_archive_command_with_one_past_courses`
**Note:**
These changes also contains isort and linting related issues fixes.

LP-2196 Write unit tests for Command archive_past_courses_communities

---

common/djangoapps/philu_commands/management/commands/autoscore_ondemand_course_ora.py
openedx/features/assessment/helpers.py
openedx/features/assessment/tests/test_helpers.py
openedx/features/philu_utils/sites.py
openedx/features/philu_utils/tests/test_sites.py

[LP-2400](https://philanthropyu.atlassian.net/browse/LP-2400)
Now command will take `--site-id={site_id}`, an extra param to get configuration from the site. If `site_id` is not provided or site for provided id does not exists then ORA days to wait constantly will default to 3 days.
- Unit tets updated
- All unit test passing
- Pylint score 10/10
- iSort ran on files

 LP-2400 Fixing ORA site configuration variable issue

---

common/djangoapps/philu_commands/management/commands/autoscore_ondemand_course_ora.py
openedx/features/assessment/helpers.py
openedx/features/assessment/tests/test_helpers.py
openedx/features/philu_utils/sites.py
openedx/features/philu_utils/tests/test_sites.py

[LP-2400](https://philanthropyu.atlassian.net/browse/LP-2400)
Now command will take `--site-id={site_id}`, an extra param to get configuration from the site. If `site_id` is not provided or site for provided id does not exists then ORA days to wait constantly will default to 3 days.
- Unit tets updated
- All unit test passing
- Pylint score 10/10
- iSort ran on files

LP-2400 Fixing ORA site configuration variable issue

---

common/djangoapps/student/views/management.py
common/lib/mandrill_client/client.py

Behavior of Reset Password Option is not Consistent on Reset Password page
[LP-1936](https://philanthropyu.atlassian.net/browse/LP-1936)
Add password change email success email on successfully changing password.

LP-1936 Behavior of Reset Password Option is not Consistent

---

.github/workflows/quality.yml

isort default behavior is to skip __init__.py file. In recent PRs regarding linting we have been adding the doc string in __init__.py file that lead to isort command to generate message "Skipped 1 file". Have added a -ns (no-skip) flag to the command.

lp-2539 Fix isort skip file issue

---

requirements/philu/base.txt

[LP-1744](https://philanthropyu.atlassian.net/browse/LP-1744)
Note:
Removing pytest mock package from base requirements as it conflicts with other packages. We have this package installed only for testing. So tests will still work.

LP-1744 Removing pytest mock package from base requirements

---

common/djangoapps/philu_commands/management/commands/send_ondemand_reminder_emails.py

[LP-2272](https://philanthropyu.atlassian.net/browse/LP-2272)
**Error log**
```
14:34:39 2021-04-20 05:34:39,462 INFO 7618 [philu_commands.management.commands.send_ondemand_reminder_emails] send_ondemand_reminder_emails.py:70 - Multiple Anonymous Ids for ranawaqar1
14:34:39 2021-04-20 05:34:39,464 INFO 7618 [philu_commands.management.commands.send_ondemand_reminder_emails] send_ondemand_reminder_emails.py:70 - Multiple Anonymous Ids for kavywodaqe
14:34:39 2021-04-20 05:34:39,467 INFO 7618 [lms.djangoapps.onboarding.helpers] helpers.py:8065 - No email preferences found for zhb12 hence considered True
14:34:39 2021-04-20 05:34:39,473 WARNING 7618 [py.warnings] locator.py:357 - /edx/app/edxapp/edx-platform/common/djangoapps/philu_commands/management/commands/send_ondemand_reminder_emails.py: …
```

LP-2272 Fixing bug in send_ondemand_reminder_emails
